apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kaniko-builder
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - get
      - list
      - watch
