apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  labels:
    app: agones
    chart: agones-1.56.0
    component: controller
    heritage: Helm
    release: agones
  name: v1.allocation.agones.dev
spec:
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURMekNDQWhlZ0F3SUJBZ0lRYnVaVEVyOUtGa1FKWnJ1ZnZHSUp5REFOQmdrcWhraUc5dzBCQVFzRkFEQWkKTVNBd0hnWURWUVFERXhkaFpHMXBjM05wYjI0dFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweU5qQXpNVGN5TVRVNApOVFZhRncwek5qQXpNVFF5TVRVNE5UVmFNQ0l4SURBZUJnTlZCQU1URjJGa2JXbHpjMmx2YmkxamIyNTBjbTlzCmJHVnlMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFxOTI1YnFHa2JISk8KSjU1K2RNSnlqUHBUQloxTldROFZSbVBuS1pEMEFTVlp1UGh0bmxKaWhhL0FWUDNCZXozYWoyeE94TnU2c01UQwpEcGZvRTllVmNxTjJsTnE2N04yWHhBZzJ3UnBjcXdnR3lyU1RRM3JOeFJhYVVScHBId2oxYUc3WXc3ZmlsK0pHCm42aU1hV1F1OFlJbWhwcXZmenNDS0VFa0E4Q2lRd011M1ZNbUJ6dWxISHNuUGp2UDQwdmFaUmRQblh5SDB0dHkKUGV0UGVXNjc0SHpJUWhCeGR2NzgvRUFqSGVQS2JYTWs3T3RCUXc4ZHNsazNKcld3V05OTHBUbTZZRTI2dWpqbQpBQmdHNkNSMDdqa0lua29wd3hGc1ZSL0pCUUxuQVM2TDJGSFdkUFRSWjNIbmtESU5MeUZoYVdTQWdQZmo1NEFCCk9STC9Ta2ZPVHdJREFRQUJvMkV3WHpBT0JnTlZIUThCQWY4RUJBTUNBcVF3SFFZRFZSMGxCQll3RkFZSUt3WUIKQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGQ1dORWdIVworVmZhNEt4ZVJoZGxoRnFlRlFMc01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQWZaS2Y2SkpLbXVmMG5UU1ovCkN4bFJiN0s3ZWRUaC80RjhYWTZmcjR2VDBMeVgrSlJIVUpHOFJBdks0dnlVZ1BEZXYrRXJ4Z1c2L1Byb1J0MXQKMXZqNDA1WDhxZEhrajgvRkNoVUN2Rjg3Y0kvTjdPKy9NaGVVZWl2Y3FmVktGb3ZUcGFRWkZtbjVmazRGeHlaMQpUbTkxYnVFckM1NU04aUFyVUlsdG9ESkxlSTBUWnorcmRTa0labG12d0JXQUprVkQ4V2xVbGtNWkdQS3ZERTFmCkFLcVg1ZjJyNHdVdlErT0gzQzBRYnNKcyt2MFN0Y0VXbUFveFVMRCs2dkpvN3pSQklxVkJhMGR4NmxrRkN6UVYKYUQ2c2NTeXAvei9rNVBsOGxla1N5bzlKaVdNM0NnSlV6SGxpeXVtK3BUeThRcmFaODU4V3JRNFRJd1UxRFd1eQpEZG9NCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  group: allocation.agones.dev
  groupPriorityMinimum: 1000
  service:
    name: agones-controller-service
    namespace: agones-system
  version: v1
  versionPriority: 15
