apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-5"
  labels:
    app: agones
    chart: agones-1.56.0
    heritage: Helm
    release: agones
  name: helm-hook-cleanup
rules:
  - apiGroups:
      - agones.dev
      - multicluster.agones.dev
      - autoscaling.agones.dev
    resources:
      - fleets
      - fleetautoscalers
      - gameservers
      - gameserversets
      - gameserverallocationpolicies
    verbs:
      - delete
      - list
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
