apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: agones
    chart: agones-1.56.0
    component: controller
    heritage: Helm
    release: agones
  name: agones-controller
  namespace: agones-system
spec:
  replicas: 2
  selector:
    matchLabels:
      agones.dev/role: controller
      app: agones
      heritage: Helm
      release: agones
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        revision/tls-cert: "1"
      labels:
        agones.dev/role: controller
        app: agones
        heritage: Helm
        release: agones
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: agones.dev/agones-system
                    operator: Exists
              weight: 1
      containers:
        - env:
            - name: MIN_PORT
              value: "7000"
            - name: MAX_PORT
              value: "8000"
            - name: SIDECAR_IMAGE
              value: us-docker.pkg.dev/agones-images/release/agones-sdk:1.56.0
            - name: ALWAYS_PULL_SIDECAR
              value: "false"
            - name: SIDECAR_CPU_REQUEST
              value: 30m
            - name: SIDECAR_CPU_LIMIT
              value: "0"
            - name: SIDECAR_MEMORY_REQUEST
              value: "0"
            - name: SIDECAR_MEMORY_LIMIT
              value: "0"
            - name: SIDECAR_RUN_AS_USER
              value: "1000"
            - name: SIDECAR_REQUESTS_RATE_LIMIT
              value: 500ms
            - name: SDK_SERVICE_ACCOUNT
              value: agones-sdk
            - name: PROMETHEUS_EXPORTER
              value: "false"
            - name: STACKDRIVER_EXPORTER
              value: "false"
            - name: STACKDRIVER_LABELS
              value: ""
            - name: GCP_PROJECT_ID
              value: ""
            - name: NUM_WORKERS
              value: "100"
            - name: MAX_CREATION_PARALLELISM
              value: "16"
            - name: MAX_GAME_SERVER_CREATIONS_PER_BATCH
              value: "64"
            - name: MAX_DELETION_PARALLELISM
              value: "64"
            - name: MAX_GAME_SERVER_DELETIONS_PER_BATCH
              value: "64"
            - name: MAX_POD_PENDING_COUNT
              value: "5000"
            - name: API_SERVER_QPS
              value: "400"
            - name: API_SERVER_QPS_BURST
              value: "500"
            - name: LOG_LEVEL
              value: info
            - name: FEATURE_GATES
              value: ""
            - name: ALLOCATION_BATCH_WAIT_TIME
              value: 500ms
            - name: CLOUD_PRODUCT
              value: auto
            - name: LOG_DIR
              value: /logs
            - name: LOG_SIZE_LIMIT_MB
              value: "10000"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONTAINER_NAME
              value: agones-controller
            - name: LEADER_ELECTION
              value: "true"
          image: us-docker.pkg.dev/agones-images/release/agones-controller:1.56.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /live
              port: http
            initialDelaySeconds: 3
            periodSeconds: 3
            timeoutSeconds: 1
          name: agones-controller
          ports:
            - containerPort: 8081
              name: webhooks
            - containerPort: 8080
              name: http
          resources:
            limits:
              ephemeral-storage: 10100Mi
            requests:
              ephemeral-storage: 10100Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
          volumeMounts:
            - mountPath: /certs
              name: certs
              readOnly: true
            - mountPath: /logs
              name: logs
              readOnly: false
      priorityClassName: agones-system
      serviceAccountName: agones-controller
      tolerations:
        - effect: NoExecute
          key: agones.dev/agones-system
          operator: Equal
          value: "true"
      volumes:
        - name: certs
          secret:
            secretName: agones-cert
        - emptyDir: {}
          name: logs
