apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    app: agones
    chart: agones-1.56.0
    component: controller
    heritage: Helm
    release: agones
  name: agones-mutation-webhook
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURNRENDQWhpZ0F3SUJBZ0lSQUtQUERiTFBnZjRMUUt0TVA2aUloYXd3RFFZSktvWklodmNOQVFFTEJRQXcKSWpFZ01CNEdBMVVFQXhNWFlXUnRhWE56YVc5dUxXTnZiblJ5YjJ4c1pYSXRZMkV3SGhjTk1qWXdNekUzTVRFegpPRFUwV2hjTk16WXdNekUwTVRFek9EVTBXakFpTVNBd0hnWURWUVFERXhkaFpHMXBjM05wYjI0dFkyOXVkSEp2CmJHeGxjaTFqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTmJsbm96RGV2Zm8KN2dubkpPWUlhU1JpblJFY1FaelcwdDdvMmc5R0pKUEZERE9PVnlMVTZqZVozSmxIUmh1TXdLZXczMGRpOHZhbApWU2lQSUNtSDQzRUppTnJRVm02ektIR2xEWGtTdjl0UTM2UjdmV3dCaituYjQ2ZnpnNFE0Q2lUd2VFUFF0ajRrCjZpY1JOa1NNNlNzWXRBVjJYempqYm8vblJMNEZUOEZJRGVHSnFNRUlDaDhPUlZ6dWVEVThMK2xibWJQQ1RNRXoKOUFmazJFMElWb1NOZEJOS2NiUEVpOStWNU5TU3FRVDdQdjNaZ000VjdSVEM2K2ZvbXpEZVlqSWpUcEVldjlWbApadm9RRlhKekJEMUR1N2lMTUtuMjVnRkhSQ203S05RYkNzMnNjbWl6VDlyemxlZkpFMUdCMEFHTDRPcFNFSndDCitSYUZIalU1SEdzQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXTUJRR0NDc0cKQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlNVS1dRSgpOOXJGdWhoOHhQNkF2QnFjdEVMU21UQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFERGZ6bDVoenM2SnU1azN5ClI3WE1reVZaamRTempLMnJlb2JSazZKU3A0THNzd2toKy92azRZcG1nTVIyUlQ1b2kveno0bkkzMWprUUZEd3EKYjRVR1M1c3ArUk4yQXhDT3VzK0k1R0RMQVlOSGlqNlNmdm9weHp1U3VRWFNGejRxSGI3Vk93ejdxMFRSYmV2UgpuMzhEWkxYN2xPRVJGZ3NyaFp3OTZqQkQyQlpmSGFtdVBEZXpFYlVUVlhtcDQ5empEWE9xaVV4VHVOSUtjRmNuClgvZEh6MEJ6UDVKWm9BWG1rQmc4WmE2dmphVldhdDRKeUJuSXdpVSs4ZjlFdEJTcHRJQkJFTnB3VWh3UldnY2oKdjlZc3cyZjZ5cWdQUTFtTEE5NHlFRENDRnp4clBwU2tpTHZWTlJodjZvYzY2WE0xb2xYUkRVV0t4VFJuNHlyYwpKekFmd1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        name: agones-controller-service
        namespace: agones-system
        path: /mutate
    failurePolicy: Fail
    name: mutations.agones.dev
    rules:
      - apiGroups:
          - agones.dev
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - gameservers
          - fleets
      - apiGroups:
          - autoscaling.agones.dev
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - fleetautoscalers
    sideEffects: None
