apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    app: agones
    chart: agones-1.56.0
    component: controller
    heritage: Helm
    release: agones
  name: agones-mutation-webhook
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURNRENDQWhpZ0F3SUJBZ0lSQUxSaTMvbkpYZFQ3WWhOWUhZd2dtWlF3RFFZSktvWklodmNOQVFFTEJRQXcKSWpFZ01CNEdBMVVFQXhNWFlXUnRhWE56YVc5dUxXTnZiblJ5YjJ4c1pYSXRZMkV3SGhjTk1qWXdNekUzTVRneApNREl3V2hjTk16WXdNekUwTVRneE1ESXdXakFpTVNBd0hnWURWUVFERXhkaFpHMXBjM05wYjI0dFkyOXVkSEp2CmJHeGxjaTFqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS1hHTGFqbUxsc3QKWWZzS0FFWnVzUElqZUR6aVZOYjdMYnhPSSs2MGhhRWQ1MTJaK2hJc3dRc3FmMjVuRU1HQkFqdExLdEVJYVZyQgowSDRYMWZtaFdjbUtXTngydSs1NkVoWjdsVHpLb0pOYVVTLzlvRzg1bUFBcHNNYWhiRjFXOW5GTmNtRGhvWXFTCk5wZ01tRlpFWG9Oa0pXTTR4RUMzSmk1MGk5YmJCU2paWXE2eUlmMk10YVFpNVBMcHhlYnJ2bFNOOFJmMUZSb08Kb1NEeWR3MHdvMFkwUEpsR0NtWTRCWE9KelhodmlqMFlxZzZjV1FpUnVmb3NMWmNNc2N6ZmFUUW8zMVhVdTJPYgowMHp0WWRUaWVvbnV0KzhzRUk5TVYzWWUvcGk2V1lEUzdoL2g0M1RMZW9KbmkzUUxkTnEzYk9MMTZ4b0Rtdm9hCmdncThYNFkxSVVrQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXTUJRR0NDc0cKQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlQ5Z21nSgpQRVhYMU1IRzBrSkpMV1hvdzFqVnZqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFUMk9hbVJwWWQyNWxzRTlkCkFScUNLdHZxL0NONlAwOFNBeHVQMktxRm1YZDU5K2VnZ1o1cTdJajhsUm1IMzkzMUF1NnZhanVENVJDb3dZOXUKNk1wWm11QWY2YkFBSTd4NGptUmhDY0UyK2NuV3ZPY3lEVVBINkdWTCs0dE9NcEE3dFJTMUl1ZjBKeDVIN3M2egpIaVRQT3JDREZvNGt0MXZZK3E5S2lSODd1WUhZQVZmemNmcjB5bEdZdDRMVlhZbHkzMmlsTlVRM2RtR01uRjM3CldnWnpDVHUvZndyd1pRdkpsTml3dmN6WU9SWFhHT3BuL1l5NEYzaVRBS0NhSlpJeDVFbUMxd1psK1I3S3BicXgKUC9sQlM2RDd5bEx2S1YwOEZUL2hRdkNPWUFVMk1UMjVmdEtjYTBNdVBUR0hHaFh4R1ZjbHVzSlhlYUFJVnJxYgpaQ1NLMWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        name: agones-controller-service
        namespace: agones-system
        path: /mutate
    failurePolicy: Fail
    name: mutations.agones.dev
    rules:
      - apiGroups:
          - agones.dev
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - gameservers
          - fleets
      - apiGroups:
          - autoscaling.agones.dev
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - fleetautoscalers
    sideEffects: None
