apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    app: agones
    chart: agones-1.56.0
    component: controller
    heritage: Helm
    release: agones
  name: zzz-agones-mutation-webhook
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURNRENDQWhpZ0F3SUJBZ0lSQUt0dUI4OVlXK2NZUkhMaWZOeUp6U2d3RFFZSktvWklodmNOQVFFTEJRQXcKSWpFZ01CNEdBMVVFQXhNWFlXUnRhWE56YVc5dUxXTnZiblJ5YjJ4c1pYSXRZMkV3SGhjTk1qWXdNekU0TVRReQpNVEl6V2hjTk16WXdNekUxTVRReU1USXpXakFpTVNBd0hnWURWUVFERXhkaFpHMXBjM05wYjI0dFkyOXVkSEp2CmJHeGxjaTFqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTTc1SWJOWU9BUTYKOG9YU1V3anNGakYyc0kyMEtYOS9Cd0NWYjJMeEF1eFZObmtpS2xNdmpSVENBWXlraUVodmNvMTRJZU1xdWR3awpDamRxejJEYUZ0VU1OUTdwS285WUlEVTVpL09IaGRjeUMxakhZTHhyNnRZRzJrZGFsRFU3ZzVya1M1UjhwWW1KCnJCUkZrU3hNQUlPWFpLTGpicDQvbWx1K1hDZmtESXB5T2NtV0d1MmhobSsxUWFCbm0weStMVnd6bkNJRGlhdm4KcWhnSHJkcXlVVUVWdEpvaDhYMENlbURWSk5IODZsUjVUSkRrbFNMTk1YanUxSzdEa0dmTXRybVcxVWpGd0hGVwpyNE9qTXdkb1h2T2dwS2gyUG9POWt1M1hZaDRVYU50aDEzZTlHWGxrR3d6VlhPME9DZEtRMTRyZnFWdUc5RTllClNOSkk2dG1LQ3drQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXTUJRR0NDc0cKQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlRKQW1nWQo2SXhZUEVuV0Q4bEVqdlBMdTJ1WlZUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFtdUlHb2x5RHpUM3JqdjE4CkxzQ1FKWkVPallRY3VNY2RBRjBHaU9aMG9uWmNBL243anVlek1qVzRnNGZkWFFSand0T0dYSkNSdmVJQ0h5UTQKQ1B2NzBoR3VJVE8rTDJ1Ty8vR1lJV1ZLM01nZFQzVEZLcGluZ25hNVZRM1BuVEpMSmtRbzA3dGVQaGVYL3ErSQpqaFlOVllGdXFYSFB0cW91WUJqQjNEZXdLa2tFbWZxZ09uREc2S1JMM0pLeFh1Q0JjN0srbE1MVmIzRE5qSnZoCjNDbE1tazd1ZGdGc2pTTitZVmZBQlB6UDkrUGRYdUFaUStkUlNnSXMrQVZsL2FMNmtyV0w2RUdDT1h4TjFQSnkKT0lFekxSekpIQjEzYWg5enp4NEs1WWpkMjlLL0FvUUN0S2lGMHo3U3BPSTQ1aTlwdHhUaUdUdVdkM2hzV0xMeQpwY3VyWEE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        name: agones-controller-service
        namespace: agones-system
        path: /mutate
    failurePolicy: Fail
    name: mutations.agones.dev
    objectSelector:
      matchLabels:
        agones.dev/port: autopilot-passthrough
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
