apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    app: agones
    chart: agones-1.56.0
    component: controller
    heritage: Helm
    release: agones
  name: zzz-agones-mutation-webhook
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURNRENDQWhpZ0F3SUJBZ0lSQVBNL3NIYmJZcnBQZW1seWJTZkIwR1l3RFFZSktvWklodmNOQVFFTEJRQXcKSWpFZ01CNEdBMVVFQXhNWFlXUnRhWE56YVc5dUxXTnZiblJ5YjJ4c1pYSXRZMkV3SGhjTk1qWXdOREUwTWpFdwpOelV3V2hjTk16WXdOREV4TWpFd056VXdXakFpTVNBd0hnWURWUVFERXhkaFpHMXBjM05wYjI0dFkyOXVkSEp2CmJHeGxjaTFqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSzBqWVIvekZtTnkKNlFlVlVPdHdGTEpDT1ZPTjZ3MTRpMFJXYW5pWFgycGs2MG1GQ1Z2bzFsaHJBTlZJeDhnNUZYN3hpN3JLSkdSWQo0ZzEvclBEVC9RSUc4a3lvUVRic0ZCSVp2a1ZhWWp1N3lWenJPTk94YTVvUFVxbkpSMHBDeHpyeExEODNwSmZPClFLL3NBTTNUNFJyS3Z1Rk1xZEk2c25hQy9DVjhTeGloaFBtYXRsZmw3WTJlQTFVT0h2MExRMUtUNjhwODVLblkKOHFLKzJQL3Qvb3RFSzgxT3JTdk5BYWFQZTdvVmN3YnZhRm9ab01tUldXbnpFOXlSdlZCcElFSHVaTmNsWGFGYQpJc0lIN21ORkpkYml1TVJjNWV6SFRRTjdEK3JOMFVLL2hWZ2o4NTNjc1VoS015UTJ1TVl0cUxIVTEwM1ZUQkd1CnNxbXpXNzI5N2wwQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXTUJRR0NDc0cKQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlNqV1J3ZQpiVHpKN3lzNTJlWWxIY2NaNi9UQi9EQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFNdnl0NU43OEZJMGxBSkUzCnpQbHYyblZKeXVXSEJuZ1BGN2M1ZEZkeGxBTlV5QlpkRFVqL2xXcERseTJjaGowTTJnOHJ3UUFPTWVVRGpFL2IKcjA3TUJRYU8yaUJKT0FOZmhhTm9YL1Vwd3JDRFNhMldzV29lTXkyK2RVUUpMSGdmN00xaXVFS3VXNXh3TlBzNgprbjdHZDZrR3VUanlPQXo3K250M3ZvcUlGUUtOZnJlRlQvL3p2ak5yOFVmWVJlUG5hMFRpYjVUcDd4L2R3UlFiCk9BUU9kbGFMZkVZOFpmeUlXU3AwZ09KZGxmSElidEdFK3A4djFZNFhrQ1lMbU03Q1gyc1kwZ283R0dPZTM3S0UKVS8vdTVNZWFPd1NOZkpJUUQ2OHNleDBpVWNjWDZEMUlVT0FPMlFKYUN5YTl6VVAyTnlmWmFEYkIzSTBNQnFiawp2N0xMUHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        name: agones-controller-service
        namespace: agones-system
        path: /mutate
    failurePolicy: Fail
    name: mutations.agones.dev
    objectSelector:
      matchLabels:
        agones.dev/port: autopilot-passthrough
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
