apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    app: agones
    chart: agones-1.56.0
    component: controller
    heritage: Helm
    release: agones
  name: zzz-agones-mutation-webhook
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURNRENDQWhpZ0F3SUJBZ0lSQVBFRFdpbUdjQkFERkZxdVNKaFJlMTh3RFFZSktvWklodmNOQVFFTEJRQXcKSWpFZ01CNEdBMVVFQXhNWFlXUnRhWE56YVc5dUxXTnZiblJ5YjJ4c1pYSXRZMkV3SGhjTk1qWXdNekUzTWpFegpNREF4V2hjTk16WXdNekUwTWpFek1EQXhXakFpTVNBd0hnWURWUVFERXhkaFpHMXBjM05wYjI0dFkyOXVkSEp2CmJHeGxjaTFqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTDdXZDN3VElma0UKVUY4eFpqRGlkQXpidzhnM01CaGp6TE9JUEhuSzQ3bUhQVW5uRURJVHVHZERZeExYbHhGRzR6V2hYVFg2R0VZdQo0bnlTN05IdGcxWm9wNWNUMGZ3M1ArL2JNUElYZWpVUS82dXJlNlY4WUgybXI4dmNtemw4dXBlTi9relFWWVdHCndZdmhjcXliN1RqbkpEZThBYTUwZndENHlGTkphVkx0MC94R2FLNCs2WHpGdEVXMWg0WWJ1ampIT3BySkVCenEKbFhnakVGcStpb2lYSkk2YlB0WU9NeGo2aGF4eHJWR0dGRTh5M3ZWS2JGcEFDaG10TEpVb2VjTjhvOThjNjJNSwpJci9jMTMvZGp0VjFuaWpZNW9BVXN2L29tdWMzR2tpdkJEZzFUaVJnZDVwZlExUUdtOERJSzc2Z2JUOENMQ3d2CnZhck9ZcVIzUUxNQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXTUJRR0NDc0cKQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlR1UWZxRQoxSk9lc01XUm91WWUxb1lZSXV2dkVUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFYUnVHRmcxOFVvQVg1RStGCmlJZkxvNnZGL3h1dW5rQStyRERsOUNpKzVmYk5MUHB0UHBTaUt2RkxRNDYrdzY0TVVTRXo5empGWEt0Q05TZGEKc1ZvL291cDJVbUFxMDlyaVF5ZDRTM3NkN1BaeHVXR2h1bnkrdVpCOWF3WEdyTzNucUZHaUcrS2pNaGtsRm9PZApMSTdqMkEzSmNrNTlGdGEzSGx4SW5HYTJDOTkyMHlxNlhzMWRQUjJxNkU0NFBROS9zQ25lSXBvRmY5ZkdJNkFBCnd0MHJjeGVQazFFVHl1K3c1OGFBcVlBTndpWkR4OFpWeWk2Qk9id0JrWlk5Z25ET3hYd0twaGJ1RENvK3ZDNmUKYU8wVWpyU08yRklQYkpRbERZZlFLak1od0g0ODBCNHFuWkhiSHlVMkpGUzJjSGpRVVJYdGEzcGxKZG1naWcxLwpSUmVCOHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        name: agones-controller-service
        namespace: agones-system
        path: /mutate
    failurePolicy: Fail
    name: mutations.agones.dev
    objectSelector:
      matchLabels:
        agones.dev/port: autopilot-passthrough
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
