apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    app: agones
    chart: agones-1.56.0
    component: controller
    heritage: Helm
    release: agones
  name: agones-mutation-webhook
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURMekNDQWhlZ0F3SUJBZ0lRVjEyQVh1eDhTQkNWTDl6SGhOd3REakFOQmdrcWhraUc5dzBCQVFzRkFEQWkKTVNBd0hnWURWUVFERXhkaFpHMXBjM05wYjI0dFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweU5qQXpNVGN4TVRRegpNRFZhRncwek5qQXpNVFF4TVRRek1EVmFNQ0l4SURBZUJnTlZCQU1URjJGa2JXbHpjMmx2YmkxamIyNTBjbTlzCmJHVnlMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF5ZklJYUN1ckxIMVQKMVd3emhnWDYvd3RYOXRXK2RZNjdQZFNhQWxJZnh1STRyaVBaaSs2WTF0VDd3YUpGSGdIQ0hFeFZtL3c2S2tNZApyb3pUNFkxdElWY2pBUWg5VEo5aVMyRGpNUDlleUZwamwwdjIyREwzOTZ4TVEwYks5NDFmNkFneC9EZGxxQ3lpCjZZSkZiUktZSWZvZDZRdWtxdkhkUldEWG9kK2Exa3pJSkhsSVcxUnRTVXBpS0FyZkxST2ZjYmtSTnJXdXhTSmkKY3NSV3EzY0w4SS9WS21oQmtOWGNsSDFjaTlwSE9PUlZZL2JMSUwzblJYR0NybkpBNG5vTFZoSE1YTEYyMHRoVwpPdGNyTGsyNkZ3K1lhbkNWUUlMaldUZGJrYmNEcWhiTDhEcXVTZVdyOTFGYnkwdWRaUjF1M2pHTC9ZWFo4MklmCmg3dEpwUzVUelFJREFRQUJvMkV3WHpBT0JnTlZIUThCQWY4RUJBTUNBcVF3SFFZRFZSMGxCQll3RkFZSUt3WUIKQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGUEtzaFczcAphNmhwdXdsUVovSmJNb3BPMkUzcE1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ2xwMEtoZUlOVHIxUVNmT2EvClE2ejFYOTlFS2xsTWFsRjIzNnVCMlFtTXVCVzcxdGlNNGk4Tm5iV3NSTmtrK1hFdXZuNmNkNnBCWnlKU3h3WDkKbElXbzdLYnJSdThrdnl1bStDcnBNemtPVGY3RFNnNHBOYVhhUFpxNXY5MnB3d0ZFWU16YjNoZGZMeUdHL0xwRwpZdFVweUVPUk53bytxZThzZEN5K2Zseng5V0hKa0hHdjY5a1RVM2lra3M5YVN1cVFFMGduaHl0Sk5JQ2NWb2UxCmlpa1lEYnRsdmZLM21OMCs3Snp0ZXFyckRKSFUzeGU4Yk10bXdkR1NpdlRYdVUwQ2VxbXJxWE5mbGtVcEdURHUKUnNvTDQ5MHZIRGRMb2RWVmJYcVhPUXRFWWprc3F4aFcvRmo4V2ZoMnA3K2FPM0VCYmpOTUdDVDVrNnhsWTBtTwpXQThyCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: agones-controller-service
        namespace: agones-system
        path: /mutate
    failurePolicy: Fail
    name: mutations.agones.dev
    rules:
      - apiGroups:
          - agones.dev
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - gameservers
          - fleets
      - apiGroups:
          - autoscaling.agones.dev
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - fleetautoscalers
    sideEffects: None
