apiVersion: v1
kind: Service
metadata:
  labels:
    app: agones
    chart: agones-1.56.0
    component: ping
    heritage: Helm
    release: agones
  name: agones-ping-http-service
  namespace: agones-system
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    agones.dev/role: ping
  type: LoadBalancer
