apiVersion: v1
kind: Service
metadata:
  labels:
    app: agones
    chart: agones-1.56.0
    heritage: Helm
    multicluster.agones.dev/role: allocator
    release: agones
  name: agones-allocator-metrics-service
  namespace: agones-system
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    multicluster.agones.dev/role: allocator
