apiVersion: v1
kind: Service
metadata:
  labels:
    app: agones
    chart: agones-1.56.0
    component: allocator
    heritage: Helm
    release: agones
  name: agones-allocator
  namespace: agones-system
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    multicluster.agones.dev/role: allocator
  type: ClusterIP
