apiVersion: v1
kind: Service
metadata:
  labels:
    agones.dev/role: controller
    app: agones
    chart: agones-1.56.0
    heritage: Helm
    release: agones
  name: agones-controller-metrics-service
  namespace: agones-system
spec:
  ports:
    - name: metrics
      port: 8080
      targetPort: http
  selector:
    agones.dev/role: controller
