apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-5"
  labels:
    app: agones
    chart: agones-1.56.0
    heritage: Helm
    release: agones
  name: helm-hook-cleanup
  namespace: agones-system
