apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    app: agones
    chart: agones-1.56.0
    component: controller
    heritage: Helm
    release: agones
  name: agones-validation-webhook
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURMekNDQWhlZ0F3SUJBZ0lRSlcrV3BQQmVveXNpRUw5M0lYc2xoekFOQmdrcWhraUc5dzBCQVFzRkFEQWkKTVNBd0hnWURWUVFERXhkaFpHMXBjM05wYjI0dFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweU5qQXpNVGt3TWpBeApOVE5hRncwek5qQXpNVFl3TWpBeE5UTmFNQ0l4SURBZUJnTlZCQU1URjJGa2JXbHpjMmx2YmkxamIyNTBjbTlzCmJHVnlMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFtOHlsTDZ4L2RwRWkKTXgwSnF5STVzV0dOTVBTSmlwTXRtY3dTUE13RkdXWkRtaXhqZUE4dXhSbmZLQVovWFErK3JLbE1aaExvMVZGLwpOd3NmZW1ZWnMrQlZYcGJPRWUrUFFpN0VPQUpWaDdLcGJhVFBkVHpjYTdvTTlmVTZJZmM4WW9VK1JiWlVqUXpnCm5nTncweGdkd2lxMlBKZ010NENMRUNoenlIaFJXQ0dicFVWUnpka1VIbVFVUjY4Q1F0Z3JwanpqTGtaTFFuNXMKN2ViaUpRcHhSb3c2OHIvanhucDVKai9HLzNaZmN4TFRTLzhEQTBzN2hZNEVaWmxFMEErSkhTRG5UMU1mUHdxVgoxU2owdnlXTmRZbW9GWlhtYUpnN0h1U3VkL2c2VXlwQlJmN2s4blowaThIZ2xIVnNzMS9hbW1rWStXbVF0SS9oCnZZTjBTWTRmQVFJREFRQUJvMkV3WHpBT0JnTlZIUThCQWY4RUJBTUNBcVF3SFFZRFZSMGxCQll3RkFZSUt3WUIKQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGTklGeFFJRgpoK3k5TDNnQVVEUDA4YVpKckpaNU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQTRwSG5HdTE1VXE4K2NNSHhiCmpPc21reTJNWDBmbkxIQmtJSkFad3FTVlU4SHp2c3E0REhOSG1ZekRYYlBqUUoyaUtINkMxK0JSK1prWTFlVGsKM2czcmE2eGptY3FHMkR5cThLZ002cFJ4aEJiZVg1M2xZeS84QjhiZ25UaXF5NnpuVzhYR0k2b3ludGFuWXFCWgpFamxYNW8zY1N5QzNQTmZLZlB3UG9JVXJURmpCbHJoOW9TdlpnL29OblFya1puTnNpVHFrYnA1TFd5MVNoOGhMCldQSGljNWJEWk44dCt1eGlEVTRVUkVsSFNoM0dzU20vYXFEbWRGa0d3aGMwMFluTGczR2hVWEtmdzgzU2FCUjcKamNwTXVUODVaanF4Y25mT1VjNFFIZU9rcml4YjhlblNPanQvTEM2TzZ2MlJIMVVVMGM0Y0wzNzB3YmlFS1dFMwpyVHhNCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: agones-controller-service
        namespace: agones-system
        path: /validate
    failurePolicy: Fail
    name: validations.agones.dev
    rules:
      - apiGroups:
          - agones.dev
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - fleets
          - gameservers
          - gameserversets
      - apiGroups:
          - agones.dev
        apiVersions:
          - v1
        operations:
          - UPDATE
        resources:
          - fleets
          - gameserversets
      - apiGroups:
          - autoscaling.agones.dev
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - fleetautoscalers
    sideEffects: None
