apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  destination:
    namespace: database
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./manifests/postgresql
    repoURL: https://github.com/thirdlf03/microservice-infra
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
