apiVersion: v1
data:
  git.commit-message-template: ""
  git.commit-sign-off: "false"
  git.commit-signing-key: ""
  git.commit-signing-method: ""
  git.email: ""
  git.user: ""
  kube.events: "false"
  log.level: info
  registries.conf: |
    registries:
      - api_url: https://ghcr.io
        credentials: secret:argocd/ghcr-credentials#token
        name: GitHub Container Registry
        prefix: ghcr.io
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: argocd-image-updater
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/version: v1.1.0
    control-plane: argocd-image-updater-controller
    helm.sh/chart: argocd-image-updater-1.1.1
  name: argocd-image-updater-config
  namespace: argocd
