apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: argocd-image-updater
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/version: v1.1.0
    control-plane: argocd-image-updater-controller
    helm.sh/chart: argocd-image-updater-1.1.1
  name: argocd-image-updater-ssh-config
  namespace: argocd
