kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: microservice-infra
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
            event-ttl: "15m"
        etcd:
          local:
            extraArgs:
              auto-compaction-mode: "periodic"
              auto-compaction-retention: "5m"
      - |
        kind: KubeletConfiguration
        imageGCHighThresholdPercent: 95
        imageGCLowThresholdPercent: 80
        evictionHard:
          nodefs.available: "2%"
          nodefs.inodesFree: "2%"
          imagefs.available: "2%"
        evictionSoft:
          nodefs.available: "5%"
          imagefs.available: "5%"
        evictionSoftGracePeriod:
          nodefs.available: "1m"
          imagefs.available: "1m"
    extraPortMappings:
      - containerPort: 30300
        hostPort: 30300
        listenAddress: "127.0.0.1"
        protocol: TCP
      - containerPort: 30081
        hostPort: 30081
        listenAddress: "127.0.0.1"
        protocol: TCP
      - containerPort: 30444
        hostPort: 30444
        listenAddress: "127.0.0.1"
        protocol: TCP
      - containerPort: 31235
        hostPort: 31235
        listenAddress: "127.0.0.1"
        protocol: TCP
      - containerPort: 30090
        hostPort: 30090
        listenAddress: "127.0.0.1"
        protocol: TCP
      - containerPort: 30093
        hostPort: 30093
        listenAddress: "127.0.0.1"
        protocol: TCP
      # Redpanda Console
      - containerPort: 30082
        hostPort: 30082
        listenAddress: "127.0.0.1"
        protocol: TCP
