apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/component: redpanda
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redpanda
    helm.sh/chart: redpanda-25.3.2
  name: redpanda-rpk-debug-bundle
  namespace: messaging
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - events
      - limitranges
      - persistentvolumeclaims
      - pods
      - pods/log
      - replicationcontrollers
      - resourcequotas
      - serviceaccounts
      - services
    verbs:
      - get
      - list
