apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: console
    app.kubernetes.io/version: v3.3.2
    helm.sh/chart: console-3.3.0
  name: redpanda-console
  namespace: messaging
