apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/component: redpanda
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redpanda
    helm.sh/chart: redpanda-25.3.2
  name: redpanda
  namespace: messaging
