apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/instance: aws-load-balancer-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/version: v3.1.0
    helm.sh/chart: aws-load-balancer-controller-3.1.0
  name: aws-load-balancer-webhook
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQUpIZ25wS0lzeGJmWDN1RUZVaUJZa3d3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOakF6TVRrd01qQXhORGxhRncwek5qQXpNVFl3TWpBeE5EbGFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUURIRjNqRUszcmF1SHEwc2xQRjFIMjZDOXA0QmlyU2llZS9HMUk1K2dxeFltU0RySUg0L1lCcQpLcExUKzlFQkFjbHNKTnJzTnE4TGFlYUxtV3dYa0w5VW9BQ2ZubmU2TU9XNEtBamFETGEyNklDWUZmQU1aU3RnCktNNXdPWlBXem1ZM0t2RDcySFltWituRllUU2RKZW8rUkZPUDRscjZLUmdqU2ZwaHI1MkpNemJoN1lzQWc3UmkKUG9RR0ozd3NoNFlYSUNCdG1BaHNzZ0hIK0FGajVoOHZwckhjYjNGc2tpVG5uVEhLcHhTaytZVGJBUFMvQ2ROQQpXem5uOFBlNlIwTHlFME5NREhoNk1qUkF5Z2h6cExYdU5BcUN3MWNEb3BMaS92aWVPQ2lybk8weHBQODVOaTZwCjUrWGlXZlYrUHdJNjhNbk9nY1ZNcm1ManZVWk04NUwzQWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVMnZkREwzYXZIbDE1czJxSEEvaWVJbVVyRHUwd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBSXpUbVVsa2x1bkwvTWpsSEY0dW1ubWt3aE8rQVRKd242TXY4aFNYYWlPM0Eyd0Jpa3ZOc1FsYjA1bUEKVlRvU21WNVVnR09lZm1nVE9XQmhpK1lsRzdBc2E0ZUZyK1lVNW9haHZUTEpKTTFXOVZURUFZbmEyRHBqTGp3eQpDNVp0YVZVMXBqUE9NUlFraFNjWkFINk1DODZaUVBDQnA3OXBKVUVBV0tScmdTc1JRY0syT2ZOVk11ZTFnVUlQCmxqeEdNRXN1dlJKSkJ0VzdMc1Rqcmd5TlRFQm9OeHJHRmhVZzFiVi9xZTJtZDJjdXFiUFFnVlNBaHBhMUhVaVkKdUo5LzEwU1p5cklCTUplZXFVcXBybm1EYkY3Z3dtT3djM2ZpMjB6QlJOTVU5U1hLUHExY2ZUczdDNkFUanJkMgpibVFpM0JlQTM4N2JXUzBNcWZoRXk4ZUU1c3M9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: kube-system
        path: /mutate-v1-pod
    failurePolicy: Ignore
    name: mpod.elbv2.k8s.aws
    namespaceSelector:
      matchExpressions:
        - key: elbv2.k8s.aws/pod-readiness-gate-inject
          operator: In
          values:
            - enabled
    objectSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values:
            - aws-load-balancer-controller
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQUpIZ25wS0lzeGJmWDN1RUZVaUJZa3d3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOakF6TVRrd01qQXhORGxhRncwek5qQXpNVFl3TWpBeE5EbGFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUURIRjNqRUszcmF1SHEwc2xQRjFIMjZDOXA0QmlyU2llZS9HMUk1K2dxeFltU0RySUg0L1lCcQpLcExUKzlFQkFjbHNKTnJzTnE4TGFlYUxtV3dYa0w5VW9BQ2ZubmU2TU9XNEtBamFETGEyNklDWUZmQU1aU3RnCktNNXdPWlBXem1ZM0t2RDcySFltWituRllUU2RKZW8rUkZPUDRscjZLUmdqU2ZwaHI1MkpNemJoN1lzQWc3UmkKUG9RR0ozd3NoNFlYSUNCdG1BaHNzZ0hIK0FGajVoOHZwckhjYjNGc2tpVG5uVEhLcHhTaytZVGJBUFMvQ2ROQQpXem5uOFBlNlIwTHlFME5NREhoNk1qUkF5Z2h6cExYdU5BcUN3MWNEb3BMaS92aWVPQ2lybk8weHBQODVOaTZwCjUrWGlXZlYrUHdJNjhNbk9nY1ZNcm1ManZVWk04NUwzQWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVMnZkREwzYXZIbDE1czJxSEEvaWVJbVVyRHUwd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBSXpUbVVsa2x1bkwvTWpsSEY0dW1ubWt3aE8rQVRKd242TXY4aFNYYWlPM0Eyd0Jpa3ZOc1FsYjA1bUEKVlRvU21WNVVnR09lZm1nVE9XQmhpK1lsRzdBc2E0ZUZyK1lVNW9haHZUTEpKTTFXOVZURUFZbmEyRHBqTGp3eQpDNVp0YVZVMXBqUE9NUlFraFNjWkFINk1DODZaUVBDQnA3OXBKVUVBV0tScmdTc1JRY0syT2ZOVk11ZTFnVUlQCmxqeEdNRXN1dlJKSkJ0VzdMc1Rqcmd5TlRFQm9OeHJHRmhVZzFiVi9xZTJtZDJjdXFiUFFnVlNBaHBhMUhVaVkKdUo5LzEwU1p5cklCTUplZXFVcXBybm1EYkY3Z3dtT3djM2ZpMjB6QlJOTVU5U1hLUHExY2ZUczdDNkFUanJkMgpibVFpM0JlQTM4N2JXUzBNcWZoRXk4ZUU1c3M9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: kube-system
        path: /mutate-v1-pod-server-id
    failurePolicy: Fail
    name: quicid.elbv2.k8s.aws
    namespaceSelector:
      matchExpressions:
        - key: elbv2.k8s.aws/quic-server-id-inject
          operator: In
          values:
            - enabled
    objectSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values:
            - aws-load-balancer-controller
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQUpIZ25wS0lzeGJmWDN1RUZVaUJZa3d3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOakF6TVRrd01qQXhORGxhRncwek5qQXpNVFl3TWpBeE5EbGFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUURIRjNqRUszcmF1SHEwc2xQRjFIMjZDOXA0QmlyU2llZS9HMUk1K2dxeFltU0RySUg0L1lCcQpLcExUKzlFQkFjbHNKTnJzTnE4TGFlYUxtV3dYa0w5VW9BQ2ZubmU2TU9XNEtBamFETGEyNklDWUZmQU1aU3RnCktNNXdPWlBXem1ZM0t2RDcySFltWituRllUU2RKZW8rUkZPUDRscjZLUmdqU2ZwaHI1MkpNemJoN1lzQWc3UmkKUG9RR0ozd3NoNFlYSUNCdG1BaHNzZ0hIK0FGajVoOHZwckhjYjNGc2tpVG5uVEhLcHhTaytZVGJBUFMvQ2ROQQpXem5uOFBlNlIwTHlFME5NREhoNk1qUkF5Z2h6cExYdU5BcUN3MWNEb3BMaS92aWVPQ2lybk8weHBQODVOaTZwCjUrWGlXZlYrUHdJNjhNbk9nY1ZNcm1ManZVWk04NUwzQWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVMnZkREwzYXZIbDE1czJxSEEvaWVJbVVyRHUwd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBSXpUbVVsa2x1bkwvTWpsSEY0dW1ubWt3aE8rQVRKd242TXY4aFNYYWlPM0Eyd0Jpa3ZOc1FsYjA1bUEKVlRvU21WNVVnR09lZm1nVE9XQmhpK1lsRzdBc2E0ZUZyK1lVNW9haHZUTEpKTTFXOVZURUFZbmEyRHBqTGp3eQpDNVp0YVZVMXBqUE9NUlFraFNjWkFINk1DODZaUVBDQnA3OXBKVUVBV0tScmdTc1JRY0syT2ZOVk11ZTFnVUlQCmxqeEdNRXN1dlJKSkJ0VzdMc1Rqcmd5TlRFQm9OeHJHRmhVZzFiVi9xZTJtZDJjdXFiUFFnVlNBaHBhMUhVaVkKdUo5LzEwU1p5cklCTUplZXFVcXBybm1EYkY3Z3dtT3djM2ZpMjB6QlJOTVU5U1hLUHExY2ZUczdDNkFUanJkMgpibVFpM0JlQTM4N2JXUzBNcWZoRXk4ZUU1c3M9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: kube-system
        path: /mutate-v1-service
    failurePolicy: Fail
    name: mservice.elbv2.k8s.aws
    objectSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values:
            - aws-load-balancer-controller
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - services
    sideEffects: None
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQUpIZ25wS0lzeGJmWDN1RUZVaUJZa3d3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOakF6TVRrd01qQXhORGxhRncwek5qQXpNVFl3TWpBeE5EbGFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUURIRjNqRUszcmF1SHEwc2xQRjFIMjZDOXA0QmlyU2llZS9HMUk1K2dxeFltU0RySUg0L1lCcQpLcExUKzlFQkFjbHNKTnJzTnE4TGFlYUxtV3dYa0w5VW9BQ2ZubmU2TU9XNEtBamFETGEyNklDWUZmQU1aU3RnCktNNXdPWlBXem1ZM0t2RDcySFltWituRllUU2RKZW8rUkZPUDRscjZLUmdqU2ZwaHI1MkpNemJoN1lzQWc3UmkKUG9RR0ozd3NoNFlYSUNCdG1BaHNzZ0hIK0FGajVoOHZwckhjYjNGc2tpVG5uVEhLcHhTaytZVGJBUFMvQ2ROQQpXem5uOFBlNlIwTHlFME5NREhoNk1qUkF5Z2h6cExYdU5BcUN3MWNEb3BMaS92aWVPQ2lybk8weHBQODVOaTZwCjUrWGlXZlYrUHdJNjhNbk9nY1ZNcm1ManZVWk04NUwzQWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVMnZkREwzYXZIbDE1czJxSEEvaWVJbVVyRHUwd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBSXpUbVVsa2x1bkwvTWpsSEY0dW1ubWt3aE8rQVRKd242TXY4aFNYYWlPM0Eyd0Jpa3ZOc1FsYjA1bUEKVlRvU21WNVVnR09lZm1nVE9XQmhpK1lsRzdBc2E0ZUZyK1lVNW9haHZUTEpKTTFXOVZURUFZbmEyRHBqTGp3eQpDNVp0YVZVMXBqUE9NUlFraFNjWkFINk1DODZaUVBDQnA3OXBKVUVBV0tScmdTc1JRY0syT2ZOVk11ZTFnVUlQCmxqeEdNRXN1dlJKSkJ0VzdMc1Rqcmd5TlRFQm9OeHJHRmhVZzFiVi9xZTJtZDJjdXFiUFFnVlNBaHBhMUhVaVkKdUo5LzEwU1p5cklCTUplZXFVcXBybm1EYkY3Z3dtT3djM2ZpMjB6QlJOTVU5U1hLUHExY2ZUczdDNkFUanJkMgpibVFpM0JlQTM4N2JXUzBNcWZoRXk4ZUU1c3M9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: kube-system
        path: /mutate-alb-target-control-namespace-v1-pod
    failurePolicy: Fail
    name: alb-target-control.namespace.elbv2.k8s.aws
    namespaceSelector:
      matchExpressions:
        - key: elbv2.k8s.aws/alb-target-control-agent-injection
          operator: In
          values:
            - enabled
    objectSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values:
            - aws-load-balancer-controller
        - key: elbv2.k8s.aws/alb-target-control-agent-inject
          operator: NotIn
          values:
            - "false"
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQUpIZ25wS0lzeGJmWDN1RUZVaUJZa3d3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOakF6TVRrd01qQXhORGxhRncwek5qQXpNVFl3TWpBeE5EbGFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUURIRjNqRUszcmF1SHEwc2xQRjFIMjZDOXA0QmlyU2llZS9HMUk1K2dxeFltU0RySUg0L1lCcQpLcExUKzlFQkFjbHNKTnJzTnE4TGFlYUxtV3dYa0w5VW9BQ2ZubmU2TU9XNEtBamFETGEyNklDWUZmQU1aU3RnCktNNXdPWlBXem1ZM0t2RDcySFltWituRllUU2RKZW8rUkZPUDRscjZLUmdqU2ZwaHI1MkpNemJoN1lzQWc3UmkKUG9RR0ozd3NoNFlYSUNCdG1BaHNzZ0hIK0FGajVoOHZwckhjYjNGc2tpVG5uVEhLcHhTaytZVGJBUFMvQ2ROQQpXem5uOFBlNlIwTHlFME5NREhoNk1qUkF5Z2h6cExYdU5BcUN3MWNEb3BMaS92aWVPQ2lybk8weHBQODVOaTZwCjUrWGlXZlYrUHdJNjhNbk9nY1ZNcm1ManZVWk04NUwzQWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVMnZkREwzYXZIbDE1czJxSEEvaWVJbVVyRHUwd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBSXpUbVVsa2x1bkwvTWpsSEY0dW1ubWt3aE8rQVRKd242TXY4aFNYYWlPM0Eyd0Jpa3ZOc1FsYjA1bUEKVlRvU21WNVVnR09lZm1nVE9XQmhpK1lsRzdBc2E0ZUZyK1lVNW9haHZUTEpKTTFXOVZURUFZbmEyRHBqTGp3eQpDNVp0YVZVMXBqUE9NUlFraFNjWkFINk1DODZaUVBDQnA3OXBKVUVBV0tScmdTc1JRY0syT2ZOVk11ZTFnVUlQCmxqeEdNRXN1dlJKSkJ0VzdMc1Rqcmd5TlRFQm9OeHJHRmhVZzFiVi9xZTJtZDJjdXFiUFFnVlNBaHBhMUhVaVkKdUo5LzEwU1p5cklCTUplZXFVcXBybm1EYkY3Z3dtT3djM2ZpMjB6QlJOTVU5U1hLUHExY2ZUczdDNkFUanJkMgpibVFpM0JlQTM4N2JXUzBNcWZoRXk4ZUU1c3M9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: kube-system
        path: /mutate-alb-target-control-object-v1-pod
    failurePolicy: Fail
    name: alb-target-control.object.elbv2.k8s.aws
    namespaceSelector:
      matchExpressions:
        - key: elbv2.k8s.aws/alb-target-control-agent-injection
          operator: DoesNotExist
    objectSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values:
            - aws-load-balancer-controller
        - key: elbv2.k8s.aws/alb-target-control-agent-inject
          operator: In
          values:
            - "true"
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQUpIZ25wS0lzeGJmWDN1RUZVaUJZa3d3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOakF6TVRrd01qQXhORGxhRncwek5qQXpNVFl3TWpBeE5EbGFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUURIRjNqRUszcmF1SHEwc2xQRjFIMjZDOXA0QmlyU2llZS9HMUk1K2dxeFltU0RySUg0L1lCcQpLcExUKzlFQkFjbHNKTnJzTnE4TGFlYUxtV3dYa0w5VW9BQ2ZubmU2TU9XNEtBamFETGEyNklDWUZmQU1aU3RnCktNNXdPWlBXem1ZM0t2RDcySFltWituRllUU2RKZW8rUkZPUDRscjZLUmdqU2ZwaHI1MkpNemJoN1lzQWc3UmkKUG9RR0ozd3NoNFlYSUNCdG1BaHNzZ0hIK0FGajVoOHZwckhjYjNGc2tpVG5uVEhLcHhTaytZVGJBUFMvQ2ROQQpXem5uOFBlNlIwTHlFME5NREhoNk1qUkF5Z2h6cExYdU5BcUN3MWNEb3BMaS92aWVPQ2lybk8weHBQODVOaTZwCjUrWGlXZlYrUHdJNjhNbk9nY1ZNcm1ManZVWk04NUwzQWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVMnZkREwzYXZIbDE1czJxSEEvaWVJbVVyRHUwd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBSXpUbVVsa2x1bkwvTWpsSEY0dW1ubWt3aE8rQVRKd242TXY4aFNYYWlPM0Eyd0Jpa3ZOc1FsYjA1bUEKVlRvU21WNVVnR09lZm1nVE9XQmhpK1lsRzdBc2E0ZUZyK1lVNW9haHZUTEpKTTFXOVZURUFZbmEyRHBqTGp3eQpDNVp0YVZVMXBqUE9NUlFraFNjWkFINk1DODZaUVBDQnA3OXBKVUVBV0tScmdTc1JRY0syT2ZOVk11ZTFnVUlQCmxqeEdNRXN1dlJKSkJ0VzdMc1Rqcmd5TlRFQm9OeHJHRmhVZzFiVi9xZTJtZDJjdXFiUFFnVlNBaHBhMUhVaVkKdUo5LzEwU1p5cklCTUplZXFVcXBybm1EYkY3Z3dtT3djM2ZpMjB6QlJOTVU5U1hLUHExY2ZUczdDNkFUanJkMgpibVFpM0JlQTM4N2JXUzBNcWZoRXk4ZUU1c3M9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: kube-system
        path: /mutate-elbv2-k8s-aws-v1beta1-targetgroupbinding
    failurePolicy: Fail
    name: mtargetgroupbinding.elbv2.k8s.aws
    rules:
      - apiGroups:
          - elbv2.k8s.aws
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - targetgroupbindings
    sideEffects: None
