apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/instance: aws-load-balancer-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/version: v3.1.0
    helm.sh/chart: aws-load-balancer-controller-3.1.0
  name: aws-load-balancer-webhook
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lRRG1hb0hxYXB5RGFpTFpWWVNHNmlwekFOQmdrcWhraUc5dzBCQVFzRkFEQXEKTVNnd0pnWURWUVFERXg5aGQzTXRiRzloWkMxaVlXeGhibU5sY2kxamIyNTBjbTlzYkdWeUxXTmhNQjRYRFRJMgpNRE14TnpFeE16ZzFPRm9YRFRNMk1ETXhOREV4TXpnMU9Gb3dLakVvTUNZR0ExVUVBeE1mWVhkekxXeHZZV1F0ClltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBTngvSHp5RzNIZW45YmhJb3RSNVpaQ05Jd2I3c0FVUU5QZEdFU1RvTVMrdWxHdUpiaFVtaEVjOQpHc050T1V0RXRHY0VaNU4xTmlpcmJHNnF6OUNtYWFucGhLbXVyVWJmZnNhd0JuaGoyUEpLVkNSNmZTZzdJUkduCjZqYlNYUTN5czluYmtuNW9QeUtmU2dmM21hZmJyOGNUb1doczB0V0YyeFJmcXlublhUUXV0VEhZTHVkcDFGL2EKZk9nR252dDMzZlVJSFNWZFdQcVBoekJaWmJmUzRQTWw2dUxvZWFRSW5qcDI1eWkvbzZNNWtjaDFpQXlCYnkyOApEdEFoV3BidG9tWVlhWkc4RDliSTNMMGpJYXFNTmNDYUVFbXliTkNtODliQk9UQ3BGMUUwTHdpQ0NPR21PRkhoCjlad0pPeUN1YjBpMHFQMHEyb1hQamlZdVhWWlljYVVDQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvQkFRREFnS2sKTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEVCVEFEQVFILwpNQjBHQTFVZERnUVdCQlRPSFExWkZOSi84MWhwTEpRajRlV205NStJM0RBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUEySTRybVRrU2VWN3JObHlJSjc2VW1KejdBTWsxeVEwaThQd0RzM29mU0Z1VUV2a3hadnVmOERUZHJ3ZzgKWkFlK3NQSnovaVo2d3JpaElxZFVsUkhMQVg1eWtmNThGNFN0NHBhYW5DclRrU0JEWStBcTBWN2syTHdjSE9KUQpicEVxUkxQV2tnZUEvVWhST2E4Q25YUzkyVEZtREpFOFRVbkd4ZmFlcnFnNEhIOHRwTi9WTUljODJ1RUhVMXlWCmRQLzJnQkR4SUNrQnd4U0hnT3p6aGs4QitQQkJMN1lBNExCSEdRMTVLZTFXdUQyNXhKL0dYa2J3NWUwSFdxcVAKS3BzM1Y5VndzN2liUXdvVWk5NnlmNUxCa0RvdWI0R3RxcVFSZW9hcG9lb1VoNnNRR3ZBOG1veWVZZGs0U1BZRApLVCsxNi9NMFpKMDR0L3VjQkxXV2pva3k5UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: kube-system
        path: /mutate-v1-pod
    failurePolicy: Ignore
    name: mpod.elbv2.k8s.aws
    namespaceSelector:
      matchExpressions:
        - key: elbv2.k8s.aws/pod-readiness-gate-inject
          operator: In
          values:
            - enabled
    objectSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values:
            - aws-load-balancer-controller
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lRRG1hb0hxYXB5RGFpTFpWWVNHNmlwekFOQmdrcWhraUc5dzBCQVFzRkFEQXEKTVNnd0pnWURWUVFERXg5aGQzTXRiRzloWkMxaVlXeGhibU5sY2kxamIyNTBjbTlzYkdWeUxXTmhNQjRYRFRJMgpNRE14TnpFeE16ZzFPRm9YRFRNMk1ETXhOREV4TXpnMU9Gb3dLakVvTUNZR0ExVUVBeE1mWVhkekxXeHZZV1F0ClltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBTngvSHp5RzNIZW45YmhJb3RSNVpaQ05Jd2I3c0FVUU5QZEdFU1RvTVMrdWxHdUpiaFVtaEVjOQpHc050T1V0RXRHY0VaNU4xTmlpcmJHNnF6OUNtYWFucGhLbXVyVWJmZnNhd0JuaGoyUEpLVkNSNmZTZzdJUkduCjZqYlNYUTN5czluYmtuNW9QeUtmU2dmM21hZmJyOGNUb1doczB0V0YyeFJmcXlublhUUXV0VEhZTHVkcDFGL2EKZk9nR252dDMzZlVJSFNWZFdQcVBoekJaWmJmUzRQTWw2dUxvZWFRSW5qcDI1eWkvbzZNNWtjaDFpQXlCYnkyOApEdEFoV3BidG9tWVlhWkc4RDliSTNMMGpJYXFNTmNDYUVFbXliTkNtODliQk9UQ3BGMUUwTHdpQ0NPR21PRkhoCjlad0pPeUN1YjBpMHFQMHEyb1hQamlZdVhWWlljYVVDQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvQkFRREFnS2sKTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEVCVEFEQVFILwpNQjBHQTFVZERnUVdCQlRPSFExWkZOSi84MWhwTEpRajRlV205NStJM0RBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUEySTRybVRrU2VWN3JObHlJSjc2VW1KejdBTWsxeVEwaThQd0RzM29mU0Z1VUV2a3hadnVmOERUZHJ3ZzgKWkFlK3NQSnovaVo2d3JpaElxZFVsUkhMQVg1eWtmNThGNFN0NHBhYW5DclRrU0JEWStBcTBWN2syTHdjSE9KUQpicEVxUkxQV2tnZUEvVWhST2E4Q25YUzkyVEZtREpFOFRVbkd4ZmFlcnFnNEhIOHRwTi9WTUljODJ1RUhVMXlWCmRQLzJnQkR4SUNrQnd4U0hnT3p6aGs4QitQQkJMN1lBNExCSEdRMTVLZTFXdUQyNXhKL0dYa2J3NWUwSFdxcVAKS3BzM1Y5VndzN2liUXdvVWk5NnlmNUxCa0RvdWI0R3RxcVFSZW9hcG9lb1VoNnNRR3ZBOG1veWVZZGs0U1BZRApLVCsxNi9NMFpKMDR0L3VjQkxXV2pva3k5UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: kube-system
        path: /mutate-v1-pod-server-id
    failurePolicy: Fail
    name: quicid.elbv2.k8s.aws
    namespaceSelector:
      matchExpressions:
        - key: elbv2.k8s.aws/quic-server-id-inject
          operator: In
          values:
            - enabled
    objectSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values:
            - aws-load-balancer-controller
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lRRG1hb0hxYXB5RGFpTFpWWVNHNmlwekFOQmdrcWhraUc5dzBCQVFzRkFEQXEKTVNnd0pnWURWUVFERXg5aGQzTXRiRzloWkMxaVlXeGhibU5sY2kxamIyNTBjbTlzYkdWeUxXTmhNQjRYRFRJMgpNRE14TnpFeE16ZzFPRm9YRFRNMk1ETXhOREV4TXpnMU9Gb3dLakVvTUNZR0ExVUVBeE1mWVhkekxXeHZZV1F0ClltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBTngvSHp5RzNIZW45YmhJb3RSNVpaQ05Jd2I3c0FVUU5QZEdFU1RvTVMrdWxHdUpiaFVtaEVjOQpHc050T1V0RXRHY0VaNU4xTmlpcmJHNnF6OUNtYWFucGhLbXVyVWJmZnNhd0JuaGoyUEpLVkNSNmZTZzdJUkduCjZqYlNYUTN5czluYmtuNW9QeUtmU2dmM21hZmJyOGNUb1doczB0V0YyeFJmcXlublhUUXV0VEhZTHVkcDFGL2EKZk9nR252dDMzZlVJSFNWZFdQcVBoekJaWmJmUzRQTWw2dUxvZWFRSW5qcDI1eWkvbzZNNWtjaDFpQXlCYnkyOApEdEFoV3BidG9tWVlhWkc4RDliSTNMMGpJYXFNTmNDYUVFbXliTkNtODliQk9UQ3BGMUUwTHdpQ0NPR21PRkhoCjlad0pPeUN1YjBpMHFQMHEyb1hQamlZdVhWWlljYVVDQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvQkFRREFnS2sKTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEVCVEFEQVFILwpNQjBHQTFVZERnUVdCQlRPSFExWkZOSi84MWhwTEpRajRlV205NStJM0RBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUEySTRybVRrU2VWN3JObHlJSjc2VW1KejdBTWsxeVEwaThQd0RzM29mU0Z1VUV2a3hadnVmOERUZHJ3ZzgKWkFlK3NQSnovaVo2d3JpaElxZFVsUkhMQVg1eWtmNThGNFN0NHBhYW5DclRrU0JEWStBcTBWN2syTHdjSE9KUQpicEVxUkxQV2tnZUEvVWhST2E4Q25YUzkyVEZtREpFOFRVbkd4ZmFlcnFnNEhIOHRwTi9WTUljODJ1RUhVMXlWCmRQLzJnQkR4SUNrQnd4U0hnT3p6aGs4QitQQkJMN1lBNExCSEdRMTVLZTFXdUQyNXhKL0dYa2J3NWUwSFdxcVAKS3BzM1Y5VndzN2liUXdvVWk5NnlmNUxCa0RvdWI0R3RxcVFSZW9hcG9lb1VoNnNRR3ZBOG1veWVZZGs0U1BZRApLVCsxNi9NMFpKMDR0L3VjQkxXV2pva3k5UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: kube-system
        path: /mutate-v1-service
    failurePolicy: Fail
    name: mservice.elbv2.k8s.aws
    objectSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values:
            - aws-load-balancer-controller
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - services
    sideEffects: None
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lRRG1hb0hxYXB5RGFpTFpWWVNHNmlwekFOQmdrcWhraUc5dzBCQVFzRkFEQXEKTVNnd0pnWURWUVFERXg5aGQzTXRiRzloWkMxaVlXeGhibU5sY2kxamIyNTBjbTlzYkdWeUxXTmhNQjRYRFRJMgpNRE14TnpFeE16ZzFPRm9YRFRNMk1ETXhOREV4TXpnMU9Gb3dLakVvTUNZR0ExVUVBeE1mWVhkekxXeHZZV1F0ClltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBTngvSHp5RzNIZW45YmhJb3RSNVpaQ05Jd2I3c0FVUU5QZEdFU1RvTVMrdWxHdUpiaFVtaEVjOQpHc050T1V0RXRHY0VaNU4xTmlpcmJHNnF6OUNtYWFucGhLbXVyVWJmZnNhd0JuaGoyUEpLVkNSNmZTZzdJUkduCjZqYlNYUTN5czluYmtuNW9QeUtmU2dmM21hZmJyOGNUb1doczB0V0YyeFJmcXlublhUUXV0VEhZTHVkcDFGL2EKZk9nR252dDMzZlVJSFNWZFdQcVBoekJaWmJmUzRQTWw2dUxvZWFRSW5qcDI1eWkvbzZNNWtjaDFpQXlCYnkyOApEdEFoV3BidG9tWVlhWkc4RDliSTNMMGpJYXFNTmNDYUVFbXliTkNtODliQk9UQ3BGMUUwTHdpQ0NPR21PRkhoCjlad0pPeUN1YjBpMHFQMHEyb1hQamlZdVhWWlljYVVDQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvQkFRREFnS2sKTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEVCVEFEQVFILwpNQjBHQTFVZERnUVdCQlRPSFExWkZOSi84MWhwTEpRajRlV205NStJM0RBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUEySTRybVRrU2VWN3JObHlJSjc2VW1KejdBTWsxeVEwaThQd0RzM29mU0Z1VUV2a3hadnVmOERUZHJ3ZzgKWkFlK3NQSnovaVo2d3JpaElxZFVsUkhMQVg1eWtmNThGNFN0NHBhYW5DclRrU0JEWStBcTBWN2syTHdjSE9KUQpicEVxUkxQV2tnZUEvVWhST2E4Q25YUzkyVEZtREpFOFRVbkd4ZmFlcnFnNEhIOHRwTi9WTUljODJ1RUhVMXlWCmRQLzJnQkR4SUNrQnd4U0hnT3p6aGs4QitQQkJMN1lBNExCSEdRMTVLZTFXdUQyNXhKL0dYa2J3NWUwSFdxcVAKS3BzM1Y5VndzN2liUXdvVWk5NnlmNUxCa0RvdWI0R3RxcVFSZW9hcG9lb1VoNnNRR3ZBOG1veWVZZGs0U1BZRApLVCsxNi9NMFpKMDR0L3VjQkxXV2pva3k5UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: kube-system
        path: /mutate-alb-target-control-namespace-v1-pod
    failurePolicy: Fail
    name: alb-target-control.namespace.elbv2.k8s.aws
    namespaceSelector:
      matchExpressions:
        - key: elbv2.k8s.aws/alb-target-control-agent-injection
          operator: In
          values:
            - enabled
    objectSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values:
            - aws-load-balancer-controller
        - key: elbv2.k8s.aws/alb-target-control-agent-inject
          operator: NotIn
          values:
            - "false"
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lRRG1hb0hxYXB5RGFpTFpWWVNHNmlwekFOQmdrcWhraUc5dzBCQVFzRkFEQXEKTVNnd0pnWURWUVFERXg5aGQzTXRiRzloWkMxaVlXeGhibU5sY2kxamIyNTBjbTlzYkdWeUxXTmhNQjRYRFRJMgpNRE14TnpFeE16ZzFPRm9YRFRNMk1ETXhOREV4TXpnMU9Gb3dLakVvTUNZR0ExVUVBeE1mWVhkekxXeHZZV1F0ClltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBTngvSHp5RzNIZW45YmhJb3RSNVpaQ05Jd2I3c0FVUU5QZEdFU1RvTVMrdWxHdUpiaFVtaEVjOQpHc050T1V0RXRHY0VaNU4xTmlpcmJHNnF6OUNtYWFucGhLbXVyVWJmZnNhd0JuaGoyUEpLVkNSNmZTZzdJUkduCjZqYlNYUTN5czluYmtuNW9QeUtmU2dmM21hZmJyOGNUb1doczB0V0YyeFJmcXlublhUUXV0VEhZTHVkcDFGL2EKZk9nR252dDMzZlVJSFNWZFdQcVBoekJaWmJmUzRQTWw2dUxvZWFRSW5qcDI1eWkvbzZNNWtjaDFpQXlCYnkyOApEdEFoV3BidG9tWVlhWkc4RDliSTNMMGpJYXFNTmNDYUVFbXliTkNtODliQk9UQ3BGMUUwTHdpQ0NPR21PRkhoCjlad0pPeUN1YjBpMHFQMHEyb1hQamlZdVhWWlljYVVDQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvQkFRREFnS2sKTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEVCVEFEQVFILwpNQjBHQTFVZERnUVdCQlRPSFExWkZOSi84MWhwTEpRajRlV205NStJM0RBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUEySTRybVRrU2VWN3JObHlJSjc2VW1KejdBTWsxeVEwaThQd0RzM29mU0Z1VUV2a3hadnVmOERUZHJ3ZzgKWkFlK3NQSnovaVo2d3JpaElxZFVsUkhMQVg1eWtmNThGNFN0NHBhYW5DclRrU0JEWStBcTBWN2syTHdjSE9KUQpicEVxUkxQV2tnZUEvVWhST2E4Q25YUzkyVEZtREpFOFRVbkd4ZmFlcnFnNEhIOHRwTi9WTUljODJ1RUhVMXlWCmRQLzJnQkR4SUNrQnd4U0hnT3p6aGs4QitQQkJMN1lBNExCSEdRMTVLZTFXdUQyNXhKL0dYa2J3NWUwSFdxcVAKS3BzM1Y5VndzN2liUXdvVWk5NnlmNUxCa0RvdWI0R3RxcVFSZW9hcG9lb1VoNnNRR3ZBOG1veWVZZGs0U1BZRApLVCsxNi9NMFpKMDR0L3VjQkxXV2pva3k5UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: kube-system
        path: /mutate-alb-target-control-object-v1-pod
    failurePolicy: Fail
    name: alb-target-control.object.elbv2.k8s.aws
    namespaceSelector:
      matchExpressions:
        - key: elbv2.k8s.aws/alb-target-control-agent-injection
          operator: DoesNotExist
    objectSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values:
            - aws-load-balancer-controller
        - key: elbv2.k8s.aws/alb-target-control-agent-inject
          operator: In
          values:
            - "true"
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lRRG1hb0hxYXB5RGFpTFpWWVNHNmlwekFOQmdrcWhraUc5dzBCQVFzRkFEQXEKTVNnd0pnWURWUVFERXg5aGQzTXRiRzloWkMxaVlXeGhibU5sY2kxamIyNTBjbTlzYkdWeUxXTmhNQjRYRFRJMgpNRE14TnpFeE16ZzFPRm9YRFRNMk1ETXhOREV4TXpnMU9Gb3dLakVvTUNZR0ExVUVBeE1mWVhkekxXeHZZV1F0ClltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBTngvSHp5RzNIZW45YmhJb3RSNVpaQ05Jd2I3c0FVUU5QZEdFU1RvTVMrdWxHdUpiaFVtaEVjOQpHc050T1V0RXRHY0VaNU4xTmlpcmJHNnF6OUNtYWFucGhLbXVyVWJmZnNhd0JuaGoyUEpLVkNSNmZTZzdJUkduCjZqYlNYUTN5czluYmtuNW9QeUtmU2dmM21hZmJyOGNUb1doczB0V0YyeFJmcXlublhUUXV0VEhZTHVkcDFGL2EKZk9nR252dDMzZlVJSFNWZFdQcVBoekJaWmJmUzRQTWw2dUxvZWFRSW5qcDI1eWkvbzZNNWtjaDFpQXlCYnkyOApEdEFoV3BidG9tWVlhWkc4RDliSTNMMGpJYXFNTmNDYUVFbXliTkNtODliQk9UQ3BGMUUwTHdpQ0NPR21PRkhoCjlad0pPeUN1YjBpMHFQMHEyb1hQamlZdVhWWlljYVVDQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvQkFRREFnS2sKTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEVCVEFEQVFILwpNQjBHQTFVZERnUVdCQlRPSFExWkZOSi84MWhwTEpRajRlV205NStJM0RBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUEySTRybVRrU2VWN3JObHlJSjc2VW1KejdBTWsxeVEwaThQd0RzM29mU0Z1VUV2a3hadnVmOERUZHJ3ZzgKWkFlK3NQSnovaVo2d3JpaElxZFVsUkhMQVg1eWtmNThGNFN0NHBhYW5DclRrU0JEWStBcTBWN2syTHdjSE9KUQpicEVxUkxQV2tnZUEvVWhST2E4Q25YUzkyVEZtREpFOFRVbkd4ZmFlcnFnNEhIOHRwTi9WTUljODJ1RUhVMXlWCmRQLzJnQkR4SUNrQnd4U0hnT3p6aGs4QitQQkJMN1lBNExCSEdRMTVLZTFXdUQyNXhKL0dYa2J3NWUwSFdxcVAKS3BzM1Y5VndzN2liUXdvVWk5NnlmNUxCa0RvdWI0R3RxcVFSZW9hcG9lb1VoNnNRR3ZBOG1veWVZZGs0U1BZRApLVCsxNi9NMFpKMDR0L3VjQkxXV2pva3k5UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: kube-system
        path: /mutate-elbv2-k8s-aws-v1beta1-targetgroupbinding
    failurePolicy: Fail
    name: mtargetgroupbinding.elbv2.k8s.aws
    rules:
      - apiGroups:
          - elbv2.k8s.aws
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - targetgroupbindings
    sideEffects: None
