apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/instance: aws-load-balancer-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/version: v3.1.0
    helm.sh/chart: aws-load-balancer-controller-3.1.0
  name: aws-load-balancer-webhook
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQVBJaXpXVDY5blNWTFZtNytTNHVuQkF3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOakF6TVRjeU1UVTROVEphRncwek5qQXpNVFF5TVRVNE5USmFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUURHVE5GRFZvR0VLM1NQRjA4NVc5UGtjbmVGaHd3cGhQa21Nck03V3l6cVpZenhkcHZKT2F4MQptOUpDeHlRNkZNN0NmejVsdjRxMmt0RWc4RkI1eThGT2djcUN0aWk4T2hGTzNuYzRTWHVBTS9aWVNScUtoUEJDCkx4MWkveEltc2pOdmFPeGcrV2ZCV1dqajFRano5aXNCTHhQK0NCcHVQM2UzVnBUOUtpN1BQaVZCZ2doa3UwYlkKa0VUZG12Y3FlZE5lWGpNTGdNVkVobGN5alVnaXEzZDNmT0ttMDRoZHJ5UmFwRWZjQll0UFkyUTA3Z2drd0FLcgpSSXhXc1l5V0VJK2QvQXV2TjNvcXFBaW5rUzVUejIzc2JXZ3RPSzNJc3BKVWw3SGs3ZWNQUkZzVG5JemtyY0NNCi81d2JLQ05NZjdaSnluandzTjQ0aTdwb0xGZHBGeER2QWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVY0RJZXZOYUQvUjhYS2E2cjhtSWY1WHMyWkdjd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBTGxxcTlCUlpINTdLZkIyZ3FXY0c5amZVNnMzOE42ZGw0YXdmc3pKMHpVNDA1ZGxnUnJOcHVSaFdQMnAKeXIwSlQ2RG5BMGEvbDJRcDRKTVVpdDMxdG5kTHp5Q041SndpcE9iWkg5Y3ZDM2E4a0ZKMmkzS2pmdys2WHpoVApDZTN5enlSK1I5b09RV1kwRHhOM1NHSU9vazdqVnR5ZXF6OVE3a1paVmFIcWRFVXE0RTNtRmpXZW42bWxxY2l1CkN6YmFNcGNURXBIM2NBNlo3ZXZaUmhYZ0ZWdDVRNzRneWVwSHRiQTBnY2FFLzZIckgyYi9NQUV6MG5kNjNGWUkKSThUMlkyWmNnWURhNWYxYVJia2dwQ1EwdjIzem5lb0FEZnNSeEowZnRLcjFLdEVTTXBiVTI0a3VyMitIK29mcwo5NjFZZERKSE1HWkNqUWRjdytpa2o5aUorbFU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: kube-system
        path: /mutate-v1-pod
    failurePolicy: Ignore
    name: mpod.elbv2.k8s.aws
    namespaceSelector:
      matchExpressions:
        - key: elbv2.k8s.aws/pod-readiness-gate-inject
          operator: In
          values:
            - enabled
    objectSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values:
            - aws-load-balancer-controller
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQVBJaXpXVDY5blNWTFZtNytTNHVuQkF3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOakF6TVRjeU1UVTROVEphRncwek5qQXpNVFF5TVRVNE5USmFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUURHVE5GRFZvR0VLM1NQRjA4NVc5UGtjbmVGaHd3cGhQa21Nck03V3l6cVpZenhkcHZKT2F4MQptOUpDeHlRNkZNN0NmejVsdjRxMmt0RWc4RkI1eThGT2djcUN0aWk4T2hGTzNuYzRTWHVBTS9aWVNScUtoUEJDCkx4MWkveEltc2pOdmFPeGcrV2ZCV1dqajFRano5aXNCTHhQK0NCcHVQM2UzVnBUOUtpN1BQaVZCZ2doa3UwYlkKa0VUZG12Y3FlZE5lWGpNTGdNVkVobGN5alVnaXEzZDNmT0ttMDRoZHJ5UmFwRWZjQll0UFkyUTA3Z2drd0FLcgpSSXhXc1l5V0VJK2QvQXV2TjNvcXFBaW5rUzVUejIzc2JXZ3RPSzNJc3BKVWw3SGs3ZWNQUkZzVG5JemtyY0NNCi81d2JLQ05NZjdaSnluandzTjQ0aTdwb0xGZHBGeER2QWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVY0RJZXZOYUQvUjhYS2E2cjhtSWY1WHMyWkdjd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBTGxxcTlCUlpINTdLZkIyZ3FXY0c5amZVNnMzOE42ZGw0YXdmc3pKMHpVNDA1ZGxnUnJOcHVSaFdQMnAKeXIwSlQ2RG5BMGEvbDJRcDRKTVVpdDMxdG5kTHp5Q041SndpcE9iWkg5Y3ZDM2E4a0ZKMmkzS2pmdys2WHpoVApDZTN5enlSK1I5b09RV1kwRHhOM1NHSU9vazdqVnR5ZXF6OVE3a1paVmFIcWRFVXE0RTNtRmpXZW42bWxxY2l1CkN6YmFNcGNURXBIM2NBNlo3ZXZaUmhYZ0ZWdDVRNzRneWVwSHRiQTBnY2FFLzZIckgyYi9NQUV6MG5kNjNGWUkKSThUMlkyWmNnWURhNWYxYVJia2dwQ1EwdjIzem5lb0FEZnNSeEowZnRLcjFLdEVTTXBiVTI0a3VyMitIK29mcwo5NjFZZERKSE1HWkNqUWRjdytpa2o5aUorbFU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: kube-system
        path: /mutate-v1-pod-server-id
    failurePolicy: Fail
    name: quicid.elbv2.k8s.aws
    namespaceSelector:
      matchExpressions:
        - key: elbv2.k8s.aws/quic-server-id-inject
          operator: In
          values:
            - enabled
    objectSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values:
            - aws-load-balancer-controller
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQVBJaXpXVDY5blNWTFZtNytTNHVuQkF3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOakF6TVRjeU1UVTROVEphRncwek5qQXpNVFF5TVRVNE5USmFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUURHVE5GRFZvR0VLM1NQRjA4NVc5UGtjbmVGaHd3cGhQa21Nck03V3l6cVpZenhkcHZKT2F4MQptOUpDeHlRNkZNN0NmejVsdjRxMmt0RWc4RkI1eThGT2djcUN0aWk4T2hGTzNuYzRTWHVBTS9aWVNScUtoUEJDCkx4MWkveEltc2pOdmFPeGcrV2ZCV1dqajFRano5aXNCTHhQK0NCcHVQM2UzVnBUOUtpN1BQaVZCZ2doa3UwYlkKa0VUZG12Y3FlZE5lWGpNTGdNVkVobGN5alVnaXEzZDNmT0ttMDRoZHJ5UmFwRWZjQll0UFkyUTA3Z2drd0FLcgpSSXhXc1l5V0VJK2QvQXV2TjNvcXFBaW5rUzVUejIzc2JXZ3RPSzNJc3BKVWw3SGs3ZWNQUkZzVG5JemtyY0NNCi81d2JLQ05NZjdaSnluandzTjQ0aTdwb0xGZHBGeER2QWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVY0RJZXZOYUQvUjhYS2E2cjhtSWY1WHMyWkdjd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBTGxxcTlCUlpINTdLZkIyZ3FXY0c5amZVNnMzOE42ZGw0YXdmc3pKMHpVNDA1ZGxnUnJOcHVSaFdQMnAKeXIwSlQ2RG5BMGEvbDJRcDRKTVVpdDMxdG5kTHp5Q041SndpcE9iWkg5Y3ZDM2E4a0ZKMmkzS2pmdys2WHpoVApDZTN5enlSK1I5b09RV1kwRHhOM1NHSU9vazdqVnR5ZXF6OVE3a1paVmFIcWRFVXE0RTNtRmpXZW42bWxxY2l1CkN6YmFNcGNURXBIM2NBNlo3ZXZaUmhYZ0ZWdDVRNzRneWVwSHRiQTBnY2FFLzZIckgyYi9NQUV6MG5kNjNGWUkKSThUMlkyWmNnWURhNWYxYVJia2dwQ1EwdjIzem5lb0FEZnNSeEowZnRLcjFLdEVTTXBiVTI0a3VyMitIK29mcwo5NjFZZERKSE1HWkNqUWRjdytpa2o5aUorbFU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: kube-system
        path: /mutate-v1-service
    failurePolicy: Fail
    name: mservice.elbv2.k8s.aws
    objectSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values:
            - aws-load-balancer-controller
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - services
    sideEffects: None
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQVBJaXpXVDY5blNWTFZtNytTNHVuQkF3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOakF6TVRjeU1UVTROVEphRncwek5qQXpNVFF5TVRVNE5USmFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUURHVE5GRFZvR0VLM1NQRjA4NVc5UGtjbmVGaHd3cGhQa21Nck03V3l6cVpZenhkcHZKT2F4MQptOUpDeHlRNkZNN0NmejVsdjRxMmt0RWc4RkI1eThGT2djcUN0aWk4T2hGTzNuYzRTWHVBTS9aWVNScUtoUEJDCkx4MWkveEltc2pOdmFPeGcrV2ZCV1dqajFRano5aXNCTHhQK0NCcHVQM2UzVnBUOUtpN1BQaVZCZ2doa3UwYlkKa0VUZG12Y3FlZE5lWGpNTGdNVkVobGN5alVnaXEzZDNmT0ttMDRoZHJ5UmFwRWZjQll0UFkyUTA3Z2drd0FLcgpSSXhXc1l5V0VJK2QvQXV2TjNvcXFBaW5rUzVUejIzc2JXZ3RPSzNJc3BKVWw3SGs3ZWNQUkZzVG5JemtyY0NNCi81d2JLQ05NZjdaSnluandzTjQ0aTdwb0xGZHBGeER2QWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVY0RJZXZOYUQvUjhYS2E2cjhtSWY1WHMyWkdjd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBTGxxcTlCUlpINTdLZkIyZ3FXY0c5amZVNnMzOE42ZGw0YXdmc3pKMHpVNDA1ZGxnUnJOcHVSaFdQMnAKeXIwSlQ2RG5BMGEvbDJRcDRKTVVpdDMxdG5kTHp5Q041SndpcE9iWkg5Y3ZDM2E4a0ZKMmkzS2pmdys2WHpoVApDZTN5enlSK1I5b09RV1kwRHhOM1NHSU9vazdqVnR5ZXF6OVE3a1paVmFIcWRFVXE0RTNtRmpXZW42bWxxY2l1CkN6YmFNcGNURXBIM2NBNlo3ZXZaUmhYZ0ZWdDVRNzRneWVwSHRiQTBnY2FFLzZIckgyYi9NQUV6MG5kNjNGWUkKSThUMlkyWmNnWURhNWYxYVJia2dwQ1EwdjIzem5lb0FEZnNSeEowZnRLcjFLdEVTTXBiVTI0a3VyMitIK29mcwo5NjFZZERKSE1HWkNqUWRjdytpa2o5aUorbFU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: kube-system
        path: /mutate-alb-target-control-namespace-v1-pod
    failurePolicy: Fail
    name: alb-target-control.namespace.elbv2.k8s.aws
    namespaceSelector:
      matchExpressions:
        - key: elbv2.k8s.aws/alb-target-control-agent-injection
          operator: In
          values:
            - enabled
    objectSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values:
            - aws-load-balancer-controller
        - key: elbv2.k8s.aws/alb-target-control-agent-inject
          operator: NotIn
          values:
            - "false"
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQVBJaXpXVDY5blNWTFZtNytTNHVuQkF3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOakF6TVRjeU1UVTROVEphRncwek5qQXpNVFF5TVRVNE5USmFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUURHVE5GRFZvR0VLM1NQRjA4NVc5UGtjbmVGaHd3cGhQa21Nck03V3l6cVpZenhkcHZKT2F4MQptOUpDeHlRNkZNN0NmejVsdjRxMmt0RWc4RkI1eThGT2djcUN0aWk4T2hGTzNuYzRTWHVBTS9aWVNScUtoUEJDCkx4MWkveEltc2pOdmFPeGcrV2ZCV1dqajFRano5aXNCTHhQK0NCcHVQM2UzVnBUOUtpN1BQaVZCZ2doa3UwYlkKa0VUZG12Y3FlZE5lWGpNTGdNVkVobGN5alVnaXEzZDNmT0ttMDRoZHJ5UmFwRWZjQll0UFkyUTA3Z2drd0FLcgpSSXhXc1l5V0VJK2QvQXV2TjNvcXFBaW5rUzVUejIzc2JXZ3RPSzNJc3BKVWw3SGs3ZWNQUkZzVG5JemtyY0NNCi81d2JLQ05NZjdaSnluandzTjQ0aTdwb0xGZHBGeER2QWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVY0RJZXZOYUQvUjhYS2E2cjhtSWY1WHMyWkdjd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBTGxxcTlCUlpINTdLZkIyZ3FXY0c5amZVNnMzOE42ZGw0YXdmc3pKMHpVNDA1ZGxnUnJOcHVSaFdQMnAKeXIwSlQ2RG5BMGEvbDJRcDRKTVVpdDMxdG5kTHp5Q041SndpcE9iWkg5Y3ZDM2E4a0ZKMmkzS2pmdys2WHpoVApDZTN5enlSK1I5b09RV1kwRHhOM1NHSU9vazdqVnR5ZXF6OVE3a1paVmFIcWRFVXE0RTNtRmpXZW42bWxxY2l1CkN6YmFNcGNURXBIM2NBNlo3ZXZaUmhYZ0ZWdDVRNzRneWVwSHRiQTBnY2FFLzZIckgyYi9NQUV6MG5kNjNGWUkKSThUMlkyWmNnWURhNWYxYVJia2dwQ1EwdjIzem5lb0FEZnNSeEowZnRLcjFLdEVTTXBiVTI0a3VyMitIK29mcwo5NjFZZERKSE1HWkNqUWRjdytpa2o5aUorbFU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: kube-system
        path: /mutate-alb-target-control-object-v1-pod
    failurePolicy: Fail
    name: alb-target-control.object.elbv2.k8s.aws
    namespaceSelector:
      matchExpressions:
        - key: elbv2.k8s.aws/alb-target-control-agent-injection
          operator: DoesNotExist
    objectSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values:
            - aws-load-balancer-controller
        - key: elbv2.k8s.aws/alb-target-control-agent-inject
          operator: In
          values:
            - "true"
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    sideEffects: None
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQVBJaXpXVDY5blNWTFZtNytTNHVuQkF3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOakF6TVRjeU1UVTROVEphRncwek5qQXpNVFF5TVRVNE5USmFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUURHVE5GRFZvR0VLM1NQRjA4NVc5UGtjbmVGaHd3cGhQa21Nck03V3l6cVpZenhkcHZKT2F4MQptOUpDeHlRNkZNN0NmejVsdjRxMmt0RWc4RkI1eThGT2djcUN0aWk4T2hGTzNuYzRTWHVBTS9aWVNScUtoUEJDCkx4MWkveEltc2pOdmFPeGcrV2ZCV1dqajFRano5aXNCTHhQK0NCcHVQM2UzVnBUOUtpN1BQaVZCZ2doa3UwYlkKa0VUZG12Y3FlZE5lWGpNTGdNVkVobGN5alVnaXEzZDNmT0ttMDRoZHJ5UmFwRWZjQll0UFkyUTA3Z2drd0FLcgpSSXhXc1l5V0VJK2QvQXV2TjNvcXFBaW5rUzVUejIzc2JXZ3RPSzNJc3BKVWw3SGs3ZWNQUkZzVG5JemtyY0NNCi81d2JLQ05NZjdaSnluandzTjQ0aTdwb0xGZHBGeER2QWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVY0RJZXZOYUQvUjhYS2E2cjhtSWY1WHMyWkdjd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBTGxxcTlCUlpINTdLZkIyZ3FXY0c5amZVNnMzOE42ZGw0YXdmc3pKMHpVNDA1ZGxnUnJOcHVSaFdQMnAKeXIwSlQ2RG5BMGEvbDJRcDRKTVVpdDMxdG5kTHp5Q041SndpcE9iWkg5Y3ZDM2E4a0ZKMmkzS2pmdys2WHpoVApDZTN5enlSK1I5b09RV1kwRHhOM1NHSU9vazdqVnR5ZXF6OVE3a1paVmFIcWRFVXE0RTNtRmpXZW42bWxxY2l1CkN6YmFNcGNURXBIM2NBNlo3ZXZaUmhYZ0ZWdDVRNzRneWVwSHRiQTBnY2FFLzZIckgyYi9NQUV6MG5kNjNGWUkKSThUMlkyWmNnWURhNWYxYVJia2dwQ1EwdjIzem5lb0FEZnNSeEowZnRLcjFLdEVTTXBiVTI0a3VyMitIK29mcwo5NjFZZERKSE1HWkNqUWRjdytpa2o5aUorbFU9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: kube-system
        path: /mutate-elbv2-k8s-aws-v1beta1-targetgroupbinding
    failurePolicy: Fail
    name: mtargetgroupbinding.elbv2.k8s.aws
    rules:
      - apiGroups:
          - elbv2.k8s.aws
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - targetgroupbindings
    sideEffects: None
