apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/instance: aws-load-balancer-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/version: v3.1.0
    helm.sh/chart: aws-load-balancer-controller-3.1.0
  name: aws-load-balancer-webhook
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lRVnJNcCtiaGlYSUNZMjljSVMxcXBoVEFOQmdrcWhraUc5dzBCQVFzRkFEQXEKTVNnd0pnWURWUVFERXg5aGQzTXRiRzloWkMxaVlXeGhibU5sY2kxamIyNTBjbTlzYkdWeUxXTmhNQjRYRFRJMgpNRFF4TkRJd01UazBNRm9YRFRNMk1EUXhNVEl3TVRrME1Gb3dLakVvTUNZR0ExVUVBeE1mWVhkekxXeHZZV1F0ClltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBS1NRZFBCYUtoZG5pQlZ1QnBDbWVnOGRxd3VtSnM3UEVBYnZMK3luZUtzVy9ESHJQeDVFdGlpagpNSGwyNG5yQkVFb3NRcmVMR0dkOWg5dUtSRU9CMnNJQ2dhWk9UcFRtWTZHNzZGdEtHdElJRGRxY1RjTDFCUmw0CllJekJLbURkSEcvNHJHQUkzbzZRRDU2M0Y1WnlSeC96TS90VHhqWlBmYXdXMk10dzh5RHVmWlJRN0lTamIrd1UKQTlPUmswMEUrWWtTWUhxaDJHK0xjc1dBMzJGOUZWVFVmdytNTFpNSnNTb2tjUlhwQlQzMFZ3TTVaMVRyL04vdApWSEVST3lRVnYzZ3pvc1lsbXYzNncrYzBKakpUTi9uc1dTS0NjU0ZTM3ZPcFpGT0RZaDRiZlAxeklBVHc5ZndPClVRbnRRbFJYcmVOMnpYd0J4U2FJbGNVdklTalc3TVVDQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvQkFRREFnS2sKTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEVCVEFEQVFILwpNQjBHQTFVZERnUVdCQlJDM0JSZEcxekZTM2xjeUJmVzFXaWZINFRBeURBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFoZDZ3S1lkNjFIVWdpNWcveTdieFQ1VzUwQzdZMEpiRUxUTlhIRzgwOVorWmpBZ0ZteTNsUk1RZGVHUGgKSGQvTEZZZkdobXdHbGtGVEd2UVVDdWt5cTl3ZXJOV1k0L0JBOXhMZzc5U0xvMDRGZ2VuaCtXMkc4c3lDSWtSNQpITmFwR2JuenV4dFhwdUFWRnVWMnlKZEFQenNaYVUvVElkcXl5SDhZbUFLUVk5VG5xZytSV3k3N1NtOEJ2alJKCnl4eUdIejZQUlpxUTFNUUVHR2RxcXQ0SG5TU3hLQXE3c0dtd2JQTkJrVnZEQ1BYRUVDSnhUOHVUa1VyUWllbFEKbmZBUXRXbGpRb1JjLzQxL3NMR1FsS2xjSk8xcldXeE0wUHNQcEQrRm80OHhuaWQ2RGRxQTZUSTdtbWVsUjBLOApiUWNjbVIza3hLMzRxQ0g1S1kvRS81TUR0Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: kube-system
        path: /validate-elbv2-k8s-aws-v1beta1-ingressclassparams
    failurePolicy: Fail
    name: vingressclassparams.elbv2.k8s.aws
    objectSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values:
            - aws-load-balancer-controller
    rules:
      - apiGroups:
          - elbv2.k8s.aws
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - ingressclassparams
    sideEffects: None
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lRVnJNcCtiaGlYSUNZMjljSVMxcXBoVEFOQmdrcWhraUc5dzBCQVFzRkFEQXEKTVNnd0pnWURWUVFERXg5aGQzTXRiRzloWkMxaVlXeGhibU5sY2kxamIyNTBjbTlzYkdWeUxXTmhNQjRYRFRJMgpNRFF4TkRJd01UazBNRm9YRFRNMk1EUXhNVEl3TVRrME1Gb3dLakVvTUNZR0ExVUVBeE1mWVhkekxXeHZZV1F0ClltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBS1NRZFBCYUtoZG5pQlZ1QnBDbWVnOGRxd3VtSnM3UEVBYnZMK3luZUtzVy9ESHJQeDVFdGlpagpNSGwyNG5yQkVFb3NRcmVMR0dkOWg5dUtSRU9CMnNJQ2dhWk9UcFRtWTZHNzZGdEtHdElJRGRxY1RjTDFCUmw0CllJekJLbURkSEcvNHJHQUkzbzZRRDU2M0Y1WnlSeC96TS90VHhqWlBmYXdXMk10dzh5RHVmWlJRN0lTamIrd1UKQTlPUmswMEUrWWtTWUhxaDJHK0xjc1dBMzJGOUZWVFVmdytNTFpNSnNTb2tjUlhwQlQzMFZ3TTVaMVRyL04vdApWSEVST3lRVnYzZ3pvc1lsbXYzNncrYzBKakpUTi9uc1dTS0NjU0ZTM3ZPcFpGT0RZaDRiZlAxeklBVHc5ZndPClVRbnRRbFJYcmVOMnpYd0J4U2FJbGNVdklTalc3TVVDQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvQkFRREFnS2sKTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEVCVEFEQVFILwpNQjBHQTFVZERnUVdCQlJDM0JSZEcxekZTM2xjeUJmVzFXaWZINFRBeURBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFoZDZ3S1lkNjFIVWdpNWcveTdieFQ1VzUwQzdZMEpiRUxUTlhIRzgwOVorWmpBZ0ZteTNsUk1RZGVHUGgKSGQvTEZZZkdobXdHbGtGVEd2UVVDdWt5cTl3ZXJOV1k0L0JBOXhMZzc5U0xvMDRGZ2VuaCtXMkc4c3lDSWtSNQpITmFwR2JuenV4dFhwdUFWRnVWMnlKZEFQenNaYVUvVElkcXl5SDhZbUFLUVk5VG5xZytSV3k3N1NtOEJ2alJKCnl4eUdIejZQUlpxUTFNUUVHR2RxcXQ0SG5TU3hLQXE3c0dtd2JQTkJrVnZEQ1BYRUVDSnhUOHVUa1VyUWllbFEKbmZBUXRXbGpRb1JjLzQxL3NMR1FsS2xjSk8xcldXeE0wUHNQcEQrRm80OHhuaWQ2RGRxQTZUSTdtbWVsUjBLOApiUWNjbVIza3hLMzRxQ0g1S1kvRS81TUR0Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: kube-system
        path: /validate-elbv2-k8s-aws-v1beta1-targetgroupbinding
    failurePolicy: Fail
    name: vtargetgroupbinding.elbv2.k8s.aws
    rules:
      - apiGroups:
          - elbv2.k8s.aws
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - targetgroupbindings
    sideEffects: None
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lRVnJNcCtiaGlYSUNZMjljSVMxcXBoVEFOQmdrcWhraUc5dzBCQVFzRkFEQXEKTVNnd0pnWURWUVFERXg5aGQzTXRiRzloWkMxaVlXeGhibU5sY2kxamIyNTBjbTlzYkdWeUxXTmhNQjRYRFRJMgpNRFF4TkRJd01UazBNRm9YRFRNMk1EUXhNVEl3TVRrME1Gb3dLakVvTUNZR0ExVUVBeE1mWVhkekxXeHZZV1F0ClltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBS1NRZFBCYUtoZG5pQlZ1QnBDbWVnOGRxd3VtSnM3UEVBYnZMK3luZUtzVy9ESHJQeDVFdGlpagpNSGwyNG5yQkVFb3NRcmVMR0dkOWg5dUtSRU9CMnNJQ2dhWk9UcFRtWTZHNzZGdEtHdElJRGRxY1RjTDFCUmw0CllJekJLbURkSEcvNHJHQUkzbzZRRDU2M0Y1WnlSeC96TS90VHhqWlBmYXdXMk10dzh5RHVmWlJRN0lTamIrd1UKQTlPUmswMEUrWWtTWUhxaDJHK0xjc1dBMzJGOUZWVFVmdytNTFpNSnNTb2tjUlhwQlQzMFZ3TTVaMVRyL04vdApWSEVST3lRVnYzZ3pvc1lsbXYzNncrYzBKakpUTi9uc1dTS0NjU0ZTM3ZPcFpGT0RZaDRiZlAxeklBVHc5ZndPClVRbnRRbFJYcmVOMnpYd0J4U2FJbGNVdklTalc3TVVDQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvQkFRREFnS2sKTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEVCVEFEQVFILwpNQjBHQTFVZERnUVdCQlJDM0JSZEcxekZTM2xjeUJmVzFXaWZINFRBeURBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFoZDZ3S1lkNjFIVWdpNWcveTdieFQ1VzUwQzdZMEpiRUxUTlhIRzgwOVorWmpBZ0ZteTNsUk1RZGVHUGgKSGQvTEZZZkdobXdHbGtGVEd2UVVDdWt5cTl3ZXJOV1k0L0JBOXhMZzc5U0xvMDRGZ2VuaCtXMkc4c3lDSWtSNQpITmFwR2JuenV4dFhwdUFWRnVWMnlKZEFQenNaYVUvVElkcXl5SDhZbUFLUVk5VG5xZytSV3k3N1NtOEJ2alJKCnl4eUdIejZQUlpxUTFNUUVHR2RxcXQ0SG5TU3hLQXE3c0dtd2JQTkJrVnZEQ1BYRUVDSnhUOHVUa1VyUWllbFEKbmZBUXRXbGpRb1JjLzQxL3NMR1FsS2xjSk8xcldXeE0wUHNQcEQrRm80OHhuaWQ2RGRxQTZUSTdtbWVsUjBLOApiUWNjbVIza3hLMzRxQ0g1S1kvRS81TUR0Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: kube-system
        path: /validate-networking-v1-ingress
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: vingress.elbv2.k8s.aws
    rules:
      - apiGroups:
          - networking.k8s.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - ingresses
    sideEffects: None
