apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/instance: aws-load-balancer-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/version: v3.1.0
    helm.sh/chart: aws-load-balancer-controller-3.1.0
  name: aws-load-balancer-webhook
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQUxVaVJIakc4VWVPRzdDVGdoclE5cTh3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOakF6TVRneE5ESXhNVGhhRncwek5qQXpNVFV4TkRJeE1UaGFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUUNqMnlDUlpvU3RRTm14WU00TXhSWFl3MTlvcVU3aTdhMWRYazRnYldJYkZIQ1IrbDVaRzBDUgp4ekQ0T1FIelpDNWQxZVVFczVNMHRtK3llZU9LZC9KdFN2S1Y2QXkvNUcvbkNtaWFxUkN0Mi9HaGY4ZnFPaUNaCjVlWlJxNlhKSFJvWENHclEzNk5sYzZPeGozNnpPVTNMbTVNUUg0TFVERXVXbTBCOHE5Q0NJME9hS05iRzRrS0kKWkVOaDNpWXhKbnNrSDM5TzhhbFFTSitScnJpVGtJNldYZTJuWWc1OWMxL2tWd0ZZWlU3ZWx3ZVpNWTdCMWJSbwpWeXZiUmozMnF3Zzd6bCtrK0s3bXEvdi9EMjBuMXF1VmloVlFXaTl0YzF6L091clo2cDM1S3lUSFBLWnQ4LzVZCmt0STJRc3dQZmFqNzdYRW5LTXhKenNSZTJPZkJ4MVJCQWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVbkVld215bHlTbWEybmI5U0NxSFpWUFFtajVvd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBRjFwZndMR0Frbzk0K1VlWW1saGwxRi96czhNU0pNcm9mSXM2dXZQRWFBREEvK25VKzVqWStSTEtGOWMKam85Qzd5WS9PSmJUQ21DdlBTUk90cVNzWWFOTElyVGx2dVRMcTZhVkE0Q1VHNEhBZEc1VWxmTXJFMG1QZjIySApkSkMya3Z2dUM4NHhhQTUwQ01QVUxHZTFNOXJqejIybEJCREZaRjVQWU10MGMxTWpUc1FoR2V1RVpkdmVPK0R5CldGalBGVS96M3pmYm9BTStBL0hpT3hSYUlOS3g5SGNzM1VFZm1vWTk5djhTRERMZmV4cDdXUXVKR2dPTXU3OTYKNnQ5bFV6RFRaL0RsUUNrNktBd0RyaVo5eEl2YWx6OXNzQ0QzS1UrMWZ0WFNhRCtuYWhjY0Nrempxd2lCUnlyQgorWDM2bWpTU096eSthYUdzS1hveEgzR1ZmVDA9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: kube-system
        path: /validate-elbv2-k8s-aws-v1beta1-ingressclassparams
    failurePolicy: Fail
    name: vingressclassparams.elbv2.k8s.aws
    objectSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values:
            - aws-load-balancer-controller
    rules:
      - apiGroups:
          - elbv2.k8s.aws
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - ingressclassparams
    sideEffects: None
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQUxVaVJIakc4VWVPRzdDVGdoclE5cTh3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOakF6TVRneE5ESXhNVGhhRncwek5qQXpNVFV4TkRJeE1UaGFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUUNqMnlDUlpvU3RRTm14WU00TXhSWFl3MTlvcVU3aTdhMWRYazRnYldJYkZIQ1IrbDVaRzBDUgp4ekQ0T1FIelpDNWQxZVVFczVNMHRtK3llZU9LZC9KdFN2S1Y2QXkvNUcvbkNtaWFxUkN0Mi9HaGY4ZnFPaUNaCjVlWlJxNlhKSFJvWENHclEzNk5sYzZPeGozNnpPVTNMbTVNUUg0TFVERXVXbTBCOHE5Q0NJME9hS05iRzRrS0kKWkVOaDNpWXhKbnNrSDM5TzhhbFFTSitScnJpVGtJNldYZTJuWWc1OWMxL2tWd0ZZWlU3ZWx3ZVpNWTdCMWJSbwpWeXZiUmozMnF3Zzd6bCtrK0s3bXEvdi9EMjBuMXF1VmloVlFXaTl0YzF6L091clo2cDM1S3lUSFBLWnQ4LzVZCmt0STJRc3dQZmFqNzdYRW5LTXhKenNSZTJPZkJ4MVJCQWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVbkVld215bHlTbWEybmI5U0NxSFpWUFFtajVvd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBRjFwZndMR0Frbzk0K1VlWW1saGwxRi96czhNU0pNcm9mSXM2dXZQRWFBREEvK25VKzVqWStSTEtGOWMKam85Qzd5WS9PSmJUQ21DdlBTUk90cVNzWWFOTElyVGx2dVRMcTZhVkE0Q1VHNEhBZEc1VWxmTXJFMG1QZjIySApkSkMya3Z2dUM4NHhhQTUwQ01QVUxHZTFNOXJqejIybEJCREZaRjVQWU10MGMxTWpUc1FoR2V1RVpkdmVPK0R5CldGalBGVS96M3pmYm9BTStBL0hpT3hSYUlOS3g5SGNzM1VFZm1vWTk5djhTRERMZmV4cDdXUXVKR2dPTXU3OTYKNnQ5bFV6RFRaL0RsUUNrNktBd0RyaVo5eEl2YWx6OXNzQ0QzS1UrMWZ0WFNhRCtuYWhjY0Nrempxd2lCUnlyQgorWDM2bWpTU096eSthYUdzS1hveEgzR1ZmVDA9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: kube-system
        path: /validate-elbv2-k8s-aws-v1beta1-targetgroupbinding
    failurePolicy: Fail
    name: vtargetgroupbinding.elbv2.k8s.aws
    rules:
      - apiGroups:
          - elbv2.k8s.aws
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - targetgroupbindings
    sideEffects: None
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURRRENDQWlpZ0F3SUJBZ0lSQUxVaVJIakc4VWVPRzdDVGdoclE5cTh3RFFZSktvWklodmNOQVFFTEJRQXcKS2pFb01DWUdBMVVFQXhNZllYZHpMV3h2WVdRdFltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVEFlRncweQpOakF6TVRneE5ESXhNVGhhRncwek5qQXpNVFV4TkRJeE1UaGFNQ294S0RBbUJnTlZCQU1USDJGM2N5MXNiMkZrCkxXSmhiR0Z1WTJWeUxXTnZiblJ5YjJ4c1pYSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXcKZ2dFS0FvSUJBUUNqMnlDUlpvU3RRTm14WU00TXhSWFl3MTlvcVU3aTdhMWRYazRnYldJYkZIQ1IrbDVaRzBDUgp4ekQ0T1FIelpDNWQxZVVFczVNMHRtK3llZU9LZC9KdFN2S1Y2QXkvNUcvbkNtaWFxUkN0Mi9HaGY4ZnFPaUNaCjVlWlJxNlhKSFJvWENHclEzNk5sYzZPeGozNnpPVTNMbTVNUUg0TFVERXVXbTBCOHE5Q0NJME9hS05iRzRrS0kKWkVOaDNpWXhKbnNrSDM5TzhhbFFTSitScnJpVGtJNldYZTJuWWc1OWMxL2tWd0ZZWlU3ZWx3ZVpNWTdCMWJSbwpWeXZiUmozMnF3Zzd6bCtrK0s3bXEvdi9EMjBuMXF1VmloVlFXaTl0YzF6L091clo2cDM1S3lUSFBLWnQ4LzVZCmt0STJRc3dQZmFqNzdYRW5LTXhKenNSZTJPZkJ4MVJCQWdNQkFBR2pZVEJmTUE0R0ExVWREd0VCL3dRRUF3SUMKcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQgovekFkQmdOVkhRNEVGZ1FVbkVld215bHlTbWEybmI5U0NxSFpWUFFtajVvd0RRWUpLb1pJaHZjTkFRRUxCUUFECmdnRUJBRjFwZndMR0Frbzk0K1VlWW1saGwxRi96czhNU0pNcm9mSXM2dXZQRWFBREEvK25VKzVqWStSTEtGOWMKam85Qzd5WS9PSmJUQ21DdlBTUk90cVNzWWFOTElyVGx2dVRMcTZhVkE0Q1VHNEhBZEc1VWxmTXJFMG1QZjIySApkSkMya3Z2dUM4NHhhQTUwQ01QVUxHZTFNOXJqejIybEJCREZaRjVQWU10MGMxTWpUc1FoR2V1RVpkdmVPK0R5CldGalBGVS96M3pmYm9BTStBL0hpT3hSYUlOS3g5SGNzM1VFZm1vWTk5djhTRERMZmV4cDdXUXVKR2dPTXU3OTYKNnQ5bFV6RFRaL0RsUUNrNktBd0RyaVo5eEl2YWx6OXNzQ0QzS1UrMWZ0WFNhRCtuYWhjY0Nrempxd2lCUnlyQgorWDM2bWpTU096eSthYUdzS1hveEgzR1ZmVDA9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: kube-system
        path: /validate-networking-v1-ingress
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: vingress.elbv2.k8s.aws
    rules:
      - apiGroups:
          - networking.k8s.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - ingresses
    sideEffects: None
