apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    app.kubernetes.io/instance: aws-load-balancer-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/version: v3.1.0
    helm.sh/chart: aws-load-balancer-controller-3.1.0
  name: aws-load-balancer-webhook
webhooks:
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lRWW54M0NSUDhwdkNuUlBrc2VULzVMakFOQmdrcWhraUc5dzBCQVFzRkFEQXEKTVNnd0pnWURWUVFERXg5aGQzTXRiRzloWkMxaVlXeGhibU5sY2kxamIyNTBjbTlzYkdWeUxXTmhNQjRYRFRJMgpNRE14TnpFNE1UQXhORm9YRFRNMk1ETXhOREU0TVRBeE5Gb3dLakVvTUNZR0ExVUVBeE1mWVhkekxXeHZZV1F0ClltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBSlNpbHA2akE5K2c2ZWpqdWljMnlaaWczTzRsYnplYlVYcXlTRDB0a0JzNFlRRm0wU2FZd0k5MApFZXA4NEthZ09INXI5VzNxVHZkREFWRDlqL0FFdmM2U25RUjNsS1V3ZmRwZXF0a0NKZGs0ZzNsSDRSbjBPUHhKCmRGL0RHcmROSFdUc2VSWUFhU0M2UVFWN21tOVR0TjZNdTZieGY3alBvQXEyTnkyb1ljUjl4YmgxeEJtMUZrOGgKQ1ZocVZ5QXZqNjVqVWp4R1kxWnhuNEpPNXdKRWN0T3hrUWNPNEFzMTc4L0tRNC9zMWp1SUlsSlJsTTJrY083bApaYjk0NDJIMlFpNEFyYnRqVTlkSjdoOWV3R20wcHU4UW45NnNxdGJ2U29zano0clZUUUFKa05sTUc5NmhON1h1Ck1GTEhJZEZ1R0Z2cXN6am41V0ZGNVMwSDFVbzNjaThDQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvQkFRREFnS2sKTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEVCVEFEQVFILwpNQjBHQTFVZERnUVdCQlFGNm1HSnBPTzZuYXI5R0tGWkFUZWhYSlJGdFRBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFTOW9HQ01mTTVDeU5LdlRvWVN6ejJRVDc0K0I5aVZrVm1adGFWYTROUDE4dy9ldnVad2JVejJDTE5xUDgKS01DajVjT3RHWk1aU1c4OGpyQ0MxeWRKdU1mT25NblY5N1UwQWZUSDZ3N0dlZ1BzRDI4ZTZObEppS1RxSzZrTwpKd1U2TUxxeThMNmNZRVJsZ2RteFo4Tm9IMUFTYndLdm5Jcm90SHlqcjQ0V1FpWXdyeHppdlpIWUR4Nkl3M3RxCnl0aGZIYWwyY1VCMXo1dXJUekQ5RTBYK0YyazFNcEgvdGUvcmNVTVVWalorMXdQdnFQclVpWVRSM3R6NFdRQWgKdHg3c0kyR2wrK2VpU0Q5UTNFRFM1Q2FzaVpab0Q5dWlBd1JzQktlWkEyeEpRaHZYdlRwNGs5U3RJQ3IxQ2xZZAorM29xMllWK3duaTcvWE44YkoyRGJ4SVVLUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: kube-system
        path: /validate-elbv2-k8s-aws-v1beta1-ingressclassparams
    failurePolicy: Fail
    name: vingressclassparams.elbv2.k8s.aws
    objectSelector:
      matchExpressions:
        - key: app.kubernetes.io/name
          operator: NotIn
          values:
            - aws-load-balancer-controller
    rules:
      - apiGroups:
          - elbv2.k8s.aws
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - ingressclassparams
    sideEffects: None
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lRWW54M0NSUDhwdkNuUlBrc2VULzVMakFOQmdrcWhraUc5dzBCQVFzRkFEQXEKTVNnd0pnWURWUVFERXg5aGQzTXRiRzloWkMxaVlXeGhibU5sY2kxamIyNTBjbTlzYkdWeUxXTmhNQjRYRFRJMgpNRE14TnpFNE1UQXhORm9YRFRNMk1ETXhOREU0TVRBeE5Gb3dLakVvTUNZR0ExVUVBeE1mWVhkekxXeHZZV1F0ClltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBSlNpbHA2akE5K2c2ZWpqdWljMnlaaWczTzRsYnplYlVYcXlTRDB0a0JzNFlRRm0wU2FZd0k5MApFZXA4NEthZ09INXI5VzNxVHZkREFWRDlqL0FFdmM2U25RUjNsS1V3ZmRwZXF0a0NKZGs0ZzNsSDRSbjBPUHhKCmRGL0RHcmROSFdUc2VSWUFhU0M2UVFWN21tOVR0TjZNdTZieGY3alBvQXEyTnkyb1ljUjl4YmgxeEJtMUZrOGgKQ1ZocVZ5QXZqNjVqVWp4R1kxWnhuNEpPNXdKRWN0T3hrUWNPNEFzMTc4L0tRNC9zMWp1SUlsSlJsTTJrY083bApaYjk0NDJIMlFpNEFyYnRqVTlkSjdoOWV3R20wcHU4UW45NnNxdGJ2U29zano0clZUUUFKa05sTUc5NmhON1h1Ck1GTEhJZEZ1R0Z2cXN6am41V0ZGNVMwSDFVbzNjaThDQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvQkFRREFnS2sKTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEVCVEFEQVFILwpNQjBHQTFVZERnUVdCQlFGNm1HSnBPTzZuYXI5R0tGWkFUZWhYSlJGdFRBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFTOW9HQ01mTTVDeU5LdlRvWVN6ejJRVDc0K0I5aVZrVm1adGFWYTROUDE4dy9ldnVad2JVejJDTE5xUDgKS01DajVjT3RHWk1aU1c4OGpyQ0MxeWRKdU1mT25NblY5N1UwQWZUSDZ3N0dlZ1BzRDI4ZTZObEppS1RxSzZrTwpKd1U2TUxxeThMNmNZRVJsZ2RteFo4Tm9IMUFTYndLdm5Jcm90SHlqcjQ0V1FpWXdyeHppdlpIWUR4Nkl3M3RxCnl0aGZIYWwyY1VCMXo1dXJUekQ5RTBYK0YyazFNcEgvdGUvcmNVTVVWalorMXdQdnFQclVpWVRSM3R6NFdRQWgKdHg3c0kyR2wrK2VpU0Q5UTNFRFM1Q2FzaVpab0Q5dWlBd1JzQktlWkEyeEpRaHZYdlRwNGs5U3RJQ3IxQ2xZZAorM29xMllWK3duaTcvWE44YkoyRGJ4SVVLUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: kube-system
        path: /validate-elbv2-k8s-aws-v1beta1-targetgroupbinding
    failurePolicy: Fail
    name: vtargetgroupbinding.elbv2.k8s.aws
    rules:
      - apiGroups:
          - elbv2.k8s.aws
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - targetgroupbindings
    sideEffects: None
  - admissionReviewVersions:
      - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lRWW54M0NSUDhwdkNuUlBrc2VULzVMakFOQmdrcWhraUc5dzBCQVFzRkFEQXEKTVNnd0pnWURWUVFERXg5aGQzTXRiRzloWkMxaVlXeGhibU5sY2kxamIyNTBjbTlzYkdWeUxXTmhNQjRYRFRJMgpNRE14TnpFNE1UQXhORm9YRFRNMk1ETXhOREU0TVRBeE5Gb3dLakVvTUNZR0ExVUVBeE1mWVhkekxXeHZZV1F0ClltRnNZVzVqWlhJdFkyOXVkSEp2Ykd4bGNpMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBSlNpbHA2akE5K2c2ZWpqdWljMnlaaWczTzRsYnplYlVYcXlTRDB0a0JzNFlRRm0wU2FZd0k5MApFZXA4NEthZ09INXI5VzNxVHZkREFWRDlqL0FFdmM2U25RUjNsS1V3ZmRwZXF0a0NKZGs0ZzNsSDRSbjBPUHhKCmRGL0RHcmROSFdUc2VSWUFhU0M2UVFWN21tOVR0TjZNdTZieGY3alBvQXEyTnkyb1ljUjl4YmgxeEJtMUZrOGgKQ1ZocVZ5QXZqNjVqVWp4R1kxWnhuNEpPNXdKRWN0T3hrUWNPNEFzMTc4L0tRNC9zMWp1SUlsSlJsTTJrY083bApaYjk0NDJIMlFpNEFyYnRqVTlkSjdoOWV3R20wcHU4UW45NnNxdGJ2U29zano0clZUUUFKa05sTUc5NmhON1h1Ck1GTEhJZEZ1R0Z2cXN6am41V0ZGNVMwSDFVbzNjaThDQXdFQUFhTmhNRjh3RGdZRFZSMFBBUUgvQkFRREFnS2sKTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEVCVEFEQVFILwpNQjBHQTFVZERnUVdCQlFGNm1HSnBPTzZuYXI5R0tGWkFUZWhYSlJGdFRBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFTOW9HQ01mTTVDeU5LdlRvWVN6ejJRVDc0K0I5aVZrVm1adGFWYTROUDE4dy9ldnVad2JVejJDTE5xUDgKS01DajVjT3RHWk1aU1c4OGpyQ0MxeWRKdU1mT25NblY5N1UwQWZUSDZ3N0dlZ1BzRDI4ZTZObEppS1RxSzZrTwpKd1U2TUxxeThMNmNZRVJsZ2RteFo4Tm9IMUFTYndLdm5Jcm90SHlqcjQ0V1FpWXdyeHppdlpIWUR4Nkl3M3RxCnl0aGZIYWwyY1VCMXo1dXJUekQ5RTBYK0YyazFNcEgvdGUvcmNVTVVWalorMXdQdnFQclVpWVRSM3R6NFdRQWgKdHg3c0kyR2wrK2VpU0Q5UTNFRFM1Q2FzaVpab0Q5dWlBd1JzQktlWkEyeEpRaHZYdlRwNGs5U3RJQ3IxQ2xZZAorM29xMllWK3duaTcvWE44YkoyRGJ4SVVLUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      service:
        name: aws-load-balancer-webhook-service
        namespace: kube-system
        path: /validate-networking-v1-ingress
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: vingress.elbv2.k8s.aws
    rules:
      - apiGroups:
          - networking.k8s.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - ingresses
    sideEffects: None
