apiVersion: v1
data:
  password: ZGV2cGFzcw==
  postgres-password: dHlLRVV4THFhWg==
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: postgresql-masterdata
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 18.3.0
    helm.sh/chart: postgresql-18.5.2
  name: postgresql-masterdata
  namespace: database
type: Opaque
