apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: opentelemetry-collector
      app.kubernetes.io/name: otel-collector
  template:
    metadata:
      labels:
        app.kubernetes.io/component: opentelemetry-collector
        app.kubernetes.io/name: otel-collector
    spec:
      containers:
        - args:
            - --config=/etc/otelcol/config.yaml
          image: otel-collector:latest
          imagePullPolicy: Never
          name: otel-collector
          ports:
            - containerPort: 4317
              name: grpc
            - containerPort: 4318
              name: http
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - mountPath: /etc/otelcol
              name: config
      volumes:
        - configMap:
            name: otel-collector-config
          name: config
